### ISSUE TITLE
使用bot触发maa领取奖励事件报错--崩溃（AppendAward方法未找到）

### ISSUE THREAD

**Issue by nikoyoke1** [MaaAssistantArknights/MaaAssistantArknights#10097]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

使用bot链接MAA，指令触发 maa领取奖励事件， maa报错崩溃
<img width="600" alt="{4C453C61-3DA3-4dfe-891F-03139E7AE24C}" src="https://github.com/user-attachments/assets/77cdec6f-57ec-4938-870b-c453ac813830">
MAA 遇到了问题
Method 'AppendAward' not found in type 'MaaWpfGui.ViewModels.UI.TaskQueueViewModel'.
解决方案
出现未知错误
详细信息
System.ArgumentException: Method 'AppendAward' not found in type 'MaaWpfGui.ViewModels.UI.TaskQueueViewModel'.
   at MaaWpfGui.Services.RemoteControl.RemoteControlService.InvokeInstanceFunction[T](Object instance, String methodName)
   at MaaWpfGui.Services.RemoteControl.RemoteControlService.<>c__DisplayClass17_0.<<LinkStart>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 太阳甩在身后
UI Version: v5.5.11452
Core Version: v5.5.11452

### 日志文件

[asst.log](https://github.com/user-attachments/files/16495639/asst.log)
[gui.log](https://github.com/user-attachments/files/16495640/gui.log)
北京时间 20:25分

### 配置信息

mumu12模拟器v4.0版本 模拟器分辨率:1600x900 DPI:240 帧率：60
操作系统：windows11
增强截图已开启
GPU加速已开启

### 截图

<img width="600" alt="{4C453C61-3DA3-4dfe-891F-03139E7AE24C}" src="https://github.com/user-attachments/assets/ff214725-045c-4be6-a2c9-6e20056f7865">
![6CD065C2C598E3C81E928B6AE6C7D354](https://github.com/user-attachments/assets/c7d27828-0580-473e-b54d-e0d4b47f910c)
机器人触发源码
<img width="371" alt="C16B16BE06ED08B1EDDC5BECFB7903C0" src="https://github.com/user-attachments/assets/f596b9b6-9a52-4e37-ae11-e49135ffb446">

<img width="413" alt="EBCDF0D9286E910A44D00DA30FE9EEFA" src="https://github.com/user-attachments/assets/441d0d35-e638-46c2-9aac-edc32a05fbea">

**Comment by ABA2396** [comment]
帮忙看下信用商店是不是也会报错

**Comment by ABA2396** [comment]
草 那这个问题应该已经存在了快一年了，这是去年9.24的改动
