### ISSUE TITLE
找不到指定的模块

### ISSUE THREAD

**Issue by YJWGLS** [MaaAssistantArknights/MaaAssistantArknights#10315]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

找不到指定的模块

### Version

MAA-v5.5.11452-win-x64

### 日志文件

[Uploading gui.log…]()

2024/8/20 晚上

### 配置信息

[gui.json](https://github.com/user-attachments/files/16684166/gui.json)

Windows 10

### 截图

The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)

### 还有别的吗？

System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by YJWGLS** [comment]
[gui.json](https://github.com/user-attachments/files/16684175/gui.json)
[gui.log](https://github.com/user-attachments/files/16684181/gui.log)

**Comment by YJWGLS** [comment]
还要上传什么

**Comment by ABA2396** [comment]
红字不都告诉你解决方案了，为什么不看呢

**Comment by status102** [comment]
参照弹窗提示 / 新手上路文档 可以自行解决

**Comment by Saratoga-Official** [comment]
会提issue不会自己看解决方法？头一次见到这样的，都去加用户群了
