### ISSUE TITLE
启用maa时 出现未知错误 然后自动退出External component has thrown an exception.

### ISSUE THREAD

**Issue by wanghuanywq** [MaaAssistantArknights/MaaAssistantArknights#10426]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue），确认我的问题未被提及

### 问题描述

可以打开maa但是一运行就报错，并且退出
VC和NET均已安装
MAA 遇到了问题
External component has thrown an exception.
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass77_0.<ConnectToEmulator>b__4()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 太阳甩在身后UI Version: v5.5.11452Core Version: v5.5.11452

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16837535/asst.log)
[gui.log](https://github.com/user-attachments/files/16837537/gui.log)
[gui.json](https://github.com/user-attachments/files/16837553/gui.json)

### 配置信息

Windows 11 家庭中文版22631.4037 mumu12 1920*1080 280 60
开不开都一样
开不开都一样

### 截图或录屏

![屏幕截图 2024-09-02 203816](https://github.com/user-attachments/assets/f44b04a1-dd96-4443-b4b1-353c43457ca4)

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/a05d14b9-5e10-4584-bf83-e3c225a96ab3)
你这连接地址我得夸你一句天才

**Comment by wanghuanywq** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/363744673-a05d14b9-5e10-4584-bf83-e3c225a96ab3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjUyNjEsIm5iZiI6MTcyNTMyNDk2MSwicGF0aCI6Ii85OTA3Mjk3NS8zNjM3NDQ2NzMtYTA1ZDE0YjktNWUxMC00NTg0LWJmODMtZTNjMjI1YTk2YWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAwNTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTk5YTM2Zjk0OTI5MTU0OGI3NjNlM2NhYjFjODc3NzAxODUyOWYxNjNmM2IzMmU3NjFiYzJjZDg4OWYyN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RMu7e8ZbDPUmikxAiMAsZ06fGU9KewWrjfhYJJs7gf8) 你这连接地址我得夸你一句天才

![屏幕截图 2024-09-03 085508](https://github.com/user-attachments/assets/5288d144-b403-47eb-99bf-ebf369070d3c)
![屏幕截图 2024-09-03 085521](https://github.com/user-attachments/assets/83f07059-38d3-42dc-8a99-a2e4597996c0)
啊 我maa里配的没问题呀

**Comment by wanghuanywq** [comment]
@ABA2396 
![屏幕截图 2024-09-03 085508](https://github.com/user-attachments/assets/b171fc99-9eef-4515-9471-d54bb826c1e3)

![屏幕截图 2024-09-03 085521](https://github.com/user-attachments/assets/29fcfc29-c5d3-4982-8acd-23d37d072121)
啊 我maa里配的没问题呀

**Comment by wanghuanywq** [comment]
@ABA2396 所以我需要改什么吗

**Comment by ABA2396** [comment]
你连接地址呢，你家模拟器的端口是 1234567890ABCDEF 啊）

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/8f0cc2eb-1d1f-49e8-b55d-b298120fce83)

**Comment by wanghuanywq** [comment]
@ABA2396 上面写的不是自动检测嘛 所以我应该在哪里找到这个地址

**Comment by wanghuanywq** [comment]
@ABA2396  手动更改了一下 现在可以了 谢了

**Comment by octopusYan** [comment]
我朋友也遇到一次，好像某种情况下连接地址会自动变成 "1234567890ABCDEF",  但是我没找到相关的字符串，费解

**Comment by wanghuanywq** [comment]
@octopusYan 我也不知道为什么 重下了好几次 每次自动识别的都是这个 手动更改倒是没问题了

**Comment by ABA2396** [comment]
> 我朋友也遇到一次，好像某种情况下连接地址会自动变成 "1234567890ABCDEF", 但是我没找到相关的字符串，费解

我去问问 mumu 那边
