### ISSUE TITLE
【日服】点击启动会自动闪退无法靠重启电脑或重装解决

### ISSUE THREAD

**Issue by Sakitoks** [MaaAssistantArknights/MaaAssistantArknights#10583]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

之前从来没有遇到过这个问题，出现时间是在上一次更新版本的时候，大概是9月初，重新下载MAA当天可以使用，但是第二天又无法使用了。
MAA 遇到了问题
Object reference not set to an instance of an object.
解决方案
出现未知错误
详细信息
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<TaskItemSelectionChanged>b__12_0()
   at Stylet.Execute.OnUIThread(Action action)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.TaskItemSelectionChanged()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

UI Version: v5.6.0
Core Version: v5.6.0
Build Time: 2024/9/6 01:35:35

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/16964217/asst.log)
[gui.log](https://github.com/user-attachments/files/16964218/gui.log)
[gui.json](https://github.com/user-attachments/files/16964221/gui.json)

### 配置信息

windows10
雷电模拟器9

**Comment by ABA2396** [comment]
没看懂你是怎么把任务列表搞乱了
![image](https://github.com/user-attachments/assets/d7ee72fe-d53a-4b0a-90e6-a195075f2bfc)
里面有两个 6 了，现在你界面上最后一栏应该是一个没名字的空任务。最简单的办法就是把 config/gui.json 删了重新设置，你要愿意自己改那你把其中一个改成 7 也行
