### ISSUE TITLE
InvalidOperationException: 调用线程无法访问此对象，因为另一个线程拥有该对象。

### ISSUE THREAD

**Issue by yyjdelete** [MaaAssistantArknights/MaaAssistantArknights#10692]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

好像是设置了`定时执行`, `强制定时启动前显示窗口`这两个选项, 然后程序会在定时执行的时候崩溃退出
看了下系统日志, 好像24号凌晨就开始报这个错了, 应该是23号更新了什么东西造成的(一直选的内测版更新)

### Version

UI Version: v5.7.0-beta.1.d026.g0a132b241
Core Version: v5.7.0-beta.1.d026.g0a132b241
Build Time: 2024/9/27 16:05:31
Resource Version: 不义之财 复刻
Resource Time: 2024/9/24 16:33:10

### 日志和配置文件

```
Application: MAA.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: 调用线程无法访问此对象，因为另一个线程拥有该对象。
   at System.Windows.Threading.Dispatcher.<VerifyAccess>g__ThrowVerifyAccess|7_0()
   at System.Windows.Application.get_MainWindow()
   at MaaWpfGui.Services.Managers.MainWindowManager.get_MainWindow()
   at MaaWpfGui.Services.Managers.MainWindowManager.Show()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.HandleScheduledStart(Int32 configIndex)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.HandleTimerLogic(DateTime currentTime)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.Timer1_Elapsed(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### 配置信息

win11(preview, 27695)

**Comment by ABA2396** [comment]
![image](https://github.com/user-attachments/assets/411fc4de-4c5e-4927-b964-26cb2bf9c409)

**Comment by yyjdelete** [comment]
配置文件已上传, log里面好像没任何崩溃信息
如果要重现的话, 修改下定时启动的时间, 在当前时间往后1分钟, 然后把窗口最小化就行

[gui.json](https://github.com/user-attachments/files/17165127/gui.json)
[gui.new.json](https://github.com/user-attachments/files/17165129/gui.new.json)



[gui.log](https://github.com/user-attachments/files/17165090/gui.log)
[asst.log](https://github.com/user-attachments/files/17165089/asst.log)

**Comment by ABA2396** [comment]
gui.bak.log 发下

**Comment by yyjdelete** [comment]
> gui.bak.log 发下

我是把日志删了重开一直跑到崩溃退出的, 没备份之前的日志

**Comment by ABA2396** [comment]
我这里复现不出来，[v5.7.0-beta.1.d026.g0a132b241](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.7.0-beta.1.d026.g0a132b241) 是包含了 f42f527015661127952aff41c2ec7b03897c7ca9 这个提交的，照理来说不会有这个问题了。重新下个完整包试试看？

**Comment by ABA2396** [comment]
![Snipaste_2024-09-27_22-32-31](https://github.com/user-attachments/assets/dd2b1e18-7a0d-4460-b5cb-3e1fd28af0f2)
![Snipaste_2024-09-27_22-32-37](https://github.com/user-attachments/assets/1bd9ed00-7c44-4b1d-a091-98b9523f9d23)

最小化的时候定时跑起来了

**Comment by yyjdelete** [comment]
> 我这里复现不出来，[v5.7.0-beta.1.d026.g0a132b241](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.7.0-beta.1.d026.g0a132b241) 是包含了 [f42f527](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/f42f527015661127952aff41c2ec7b03897c7ca9) 这个提交的，照理来说不会有这个问题了。重新下个完整包试试看？

那就不知道为啥了, 我这边能稳定重现, 但log文件里面没有相关信息, 只能在`Win+X/日志查看器/Windows日志/应用程序`里面看到崩溃
步骤: 
1. 下个新的预览版, 解压
https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.7.0-beta.1.d026.g0a132b241
2. Skip 设置指引
3. 设置/定时执行, 勾选`强制定时启动`和`强制定时启动前显示窗口`(两个都打勾)
4. 勾选`定时1`, 设置时间为电脑时间往后1~2分钟
5. 最小化MAA窗口, 等1分钟设置的那个时间到

**Comment by yyjdelete** [comment]
> 最小化的时候定时跑起来了

是不是`强制定时启动前显示窗口`没打钩的原因

**Comment by ABA2396** [comment]
也可能，等下看看

**Comment by ABA2396** [comment]
现在发个测试版，大概半个小时之后能打出来
