### ISSUE TITLE
上午还在用，下午突然无法打开maa，有下述报错，但是重下解决问题

### ISSUE THREAD

**Issue by afdd64** [MaaAssistantArknights/MaaAssistantArknights#10859]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
	The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.<>c.<.ctor>b__12_0(String s)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

5.7.0

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17442328/asst.log)
[gui.log](https://github.com/user-attachments/files/17442331/gui.log)
[asst.bak.log](https://github.com/user-attac
[gui.json](https://github.com/user-attachments/files/17442335/gui.json)
hments/files/17442334/asst.bak.log)
缺失asst.bak.log

### 配置信息

win10 mumu12 1920*1080 280 60 已开启截图增强

**Comment by feilongproject** [comment]
升级.Net库版本到8.0
https://dotnet.microsoft.com/zh-cn/download/dotnet/8.0

**Comment by Saratoga-Official** [comment]
win + r 输入 cmd 回车
输入
winget install Microsoft.VCRedist.2015+.x64 Microsoft.DotNet.DesktopRuntime.8 
回车等装完之后重启电脑
