### ISSUE TITLE
动态链接库初始化例程失败

### ISSUE THREAD

**Issue by Alirea10** [MaaAssistantArknights/MaaAssistantArknights#10900]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

在使用MAA时，会出现报错如图（图中右侧为复制了一份的独立运行的v5.7.0maa，图左为出现问题的独立运行的maa）
![fe101f049a26580f9663f98692374023](https://github.com/user-attachments/assets/186ba55e-cae5-44a1-9a45-88fd98737f26)
```
报错文本：
The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.<>c.<.ctor>b__12_0(String s)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

### Version

v5.7.0 和v5.8.0-beta.2

### 日志和配置文件

以下为在v2.7.0 报错时产生的log
[asst.log](https://github.com/user-attachments/files/17485386/asst.log)
[gui.log](https://github.com/user-attachments/files/17485388/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17485389/asst.bak.log)
以下为 下载全新的v2.8.0.beta.2中，直接运行maa.exe时产生的日志文件，可能由于是第一次启动，未产生其他文件。
[gui (1).log](https://github.com/user-attachments/files/17485387/gui.1.log)

### 配置信息

以下为系统环境
![image](https://github.com/user-attachments/assets/1e2e9bda-2f2b-4b20-9667-989539814431)
以下为使用的模拟器版本，尽管这个问题应该与模拟器无关：
![image](https://github.com/user-attachments/assets/a1e61dc1-fb1e-47d7-bec7-10c85fc632fb)

### 还有别的吗？

关于运行maa的电脑：
之前未出现过类似的问题
大概率没有硬件方面的问题，因为其他程序/游戏看起来运行正常
重装maa没用，只要关闭了maa就再也开不起来另一个了，当前还在运行的maa运行正常
这台机器常开maa，隔段时间（指MUMU运行很久就会卡死之后）重启模拟器，常不关机
常运行MC 1.7.0server GTNH服务器整合包
前段时间安装了VMware 17

**Comment by Rbqwow** [comment]
更新运行库
