### ISSUE TITLE
动态链接库(DLL)初始化例程失败

### ISSUE THREAD

**Issue by Afavorite** [MaaAssistantArknights/MaaAssistantArknights#10939]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
	The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.<>c.<.ctor>b__12_0(String s)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

我已经无法打开MAA

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17532384/asst.log)
[gui.log](https://github.com/user-attachments/files/17532385/gui.log)
[asst.bak.zip](https://github.com/user-attachments/files/17532393/asst.bak.zip)
gui.bak没有

[gui.json](https://github.com/user-attachments/files/17532391/gui.json)

### 配置信息

操作系统：win11
模拟器：MUMU模拟器12，开启截图增强

### 截图或录屏

![{74362DFC-692D-47E4-8D9B-C600CD8B04E3}](https://github.com/user-attachments/assets/484dd0f7-5953-40de-90a4-2b29fc37477f)

**Comment by status102** [comment]
![image](https://github.com/user-attachments/assets/3455e287-2f31-4c0b-bfb1-5c87c4780ea9)
![image](https://github.com/user-attachments/assets/d190f7b7-5fe0-427e-a198-c56e471cfc51)
![image](https://github.com/user-attachments/assets/49247dd0-4a55-4dcb-999c-ea57c02d6acd)
![6KHLJ7I4IVEK2K{FEVU7K)C](https://github.com/user-attachments/assets/38106df4-0843-4b0d-904d-c976e47041ea)

**Comment by Arknights-aNsEL** [comment]
已解决，尝试更新VC_redist至更高版本
