### ISSUE TITLE
动态链接库(DLL)初始化例程失败

### ISSUE THREAD

**Issue by kdashl** [MaaAssistantArknights/MaaAssistantArknights#10938]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

启动直接弹窗报错

MAA 遇到了问题
	The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.<>c.<.ctor>b__12_0(String s)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

软件无法打开,实际为最新版

### 日志和配置文件

[gui.log](https://github.com/user-attachments/files/17532241/gui.log)

### 配置信息

还没导模拟器

### 截图或录屏

1

### 还有别的吗？

1

**Comment by sms20180130** [comment]
same here

**Comment by kdashl** [comment]
来自KdashL邮箱。
--------------------邮件已收到

**Comment by sms20180130** [comment]
https://aka.ms/vs/17/release/vc_redist.x64.exe  need update to 14.40.33816

**Comment by prochorus1999** [comment]
遇到了同样的问题
Unable to load DLL 'MaaCore.dll' or one of its dependencies

**Comment by status102** [comment]
![image](https://github.com/user-attachments/assets/07733ca7-7550-4c04-b7ee-a8edeb2dfd22)

![image](https://github.com/user-attachments/assets/3455e287-2f31-4c0b-bfb1-5c87c4780ea9)
![image](https://github.com/user-attachments/assets/d190f7b7-5fe0-427e-a198-c56e471cfc51)
![image](https://github.com/user-attachments/assets/49247dd0-4a55-4dcb-999c-ea57c02d6acd)
![6KHLJ7I4IVEK2K{FEVU7K)C](https://github.com/user-attachments/assets/38106df4-0843-4b0d-904d-c976e47041ea)

**Comment by Arknights-aNsEL** [comment]
尝试将VC_redist更新至更高版本可能解决问题

**Comment by ABA2396** [comment]
> > 尝试将VC_redist更新至更高版本可能解决问题
> 
> 5.7 是可以的,我还原了老的版本...5.8出现的这个问题.你们肯定改了啥.导致了这个不兼容

新版 sdk 打出来的包低版本运行库跑不了，就这么简单，要么你就一直不更新，新功能都别用

**Comment by eveningmoonka** [comment]
更新了还是不可以
![Screenshot 2024-12-10 193222](https://github.com/user-attachments/assets/3307b200-b294-4d77-aaac-b7f5ac87a686)

**Comment by ABA2396** [comment]
> 更新了还是不可以 ![Screenshot 2024-12-10 193222](https://private-user-images.githubusercontent.com/131318136/394254356-3307b200-b294-4d77-aaac-b7f5ac87a686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzA3NjEsIm5iZiI6MTczMzgzMDQ2MSwicGF0aCI6Ii8xMzEzMTgxMzYvMzk0MjU0MzU2LTMzMDdiMjAwLWIyOTQtNGQ3Ny1hYWFjLWI3ZjVhYzg3YTY4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxMTM0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGQyMTNjNWRiMDVjOGYwOTg1ZjJmMzUxODYzODg0ZjY3ZDgyZTgwZDY2MmRiMDBkZWYyZjFlNWM0MzQ4OGM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dgrW6650X00wgEmf_qdYnVr5WWKFPxIav6xWZaz8ds4)

那就手动点进去那两个链接进去下，还是不行就把老的运行库卸了重新安装
