### ISSUE TITLE
Can't seems to run program now after update. Tried reinstalling and install previous version too also tried reinstalling everything needed like .NET

### ISSUE THREAD

**Issue by ZuraJura** [MaaAssistantArknights/MaaAssistantArknights#10932]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

MAA has encountered an error
	The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
Solution
	Please refer to the documentation: 「FAQ - Crashes」 to solve.
Details
System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.<>c.<.ctor>b__12_0(String s)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

5.8.0

### Log and config files

[gui.json](https://github.com/user-attachments/files/17530540/gui.json)
[gui.log](https://github.com/user-attachments/files/17530542/gui.log)

### Configuration information

Windows 10
MuMu Emulator 12
1600 X 900
60 FPS

Can't seems to find "Screenshot Enhancement" settings but it's default including GPU settings.
I can't seems to find the settings for both of these but they should be in defaul as I've never change anything.

### Screenshots or recordings

There's nothing in debug folder

### Anthing else?

The issue started just recently. Was running fine a few hours ago like 6 hours ago. Tried reinsalling older version 5.7.0 run fine for few minutes then starts showing error again.
<img width="449" alt="cnt" src="https://github.com/user-attachments/assets/ca089cec-500e-4375-80ca-2c91587bf99e">

**Comment by Rbqwow** [comment]
try to run this command in terminal

```
winget install Microsoft.VCRedist.2015+.x64 Microsoft.DotNet.DesktopRuntime.8
```

**Comment by ZuraJura** [comment]
> try to run this command in terminal
> 
> ```
> winget install Microsoft.VCRedist.2015+.x64 Microsoft.DotNet.DesktopRuntime.8
> ```

already tried it before posting.didn't work

**Comment by ABA2396** [comment]
That's the problem with the runtime libraries, are you sure your VCRedist is up to date?
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by ZuraJura** [comment]
> Warning
> 
> 存在未确认的链接，请谨慎访问。 There are unconfirmed links, please visit with caution.
> 
> That's the problem with the runtime libraries, are you sure your VCRedist is up to date? https://aka.ms/vs/17/release/vc_redist.x64.exe

Ok NOW it works. thank you very much
