### ISSUE TITLE
最新内测（24.11.01晚8点）版推送安装后闪退

### ISSUE THREAD

**Issue by 68star89** [MaaAssistantArknights/MaaAssistantArknights#10998]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
	The input string 'MAX' was not in a correct format.
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.FormatException: The input string 'MAX' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Convert.ToInt32(String value)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

maa打不开，看不到具体版本号（

### 配置信息

Win11 23H2

**Comment by ABA2396** [comment]
之前有个内测版默认值给错了，之前 @status102 又把 string 解析换成了 int，这下 MAX 不认了）
你把 gui.json 里的 "Roguelike.Difficulty": "MAX",  这一行删了就好了

**Comment by status102** [comment]
> 之前有个内测版默认值给错了，之前 @status102 又把 string 解析换成了 int，这下 MAX 不认了）
> 你把 gui.json 里的 "Roguelike.Difficulty": "MAX",  这一行删了就好了

还在想默认值不是intMax吗，config里面的max是哪来的，以为自己写错（

**Comment by 68star89** [comment]
其实我觉得这个Issue应该开放一段时间再关的，毕竟今晚出这问题的人应该不少（

**Comment by status102** [comment]
> 其实我觉得这个Issue应该开放一段时间再关的，毕竟今晚出这问题的人应该不少（

关掉也能看到的

**Comment by Saratoga-Official** [comment]
> 关掉的话第一时间点开issue发现不了，你看这不是又有人发issue了（

issue选项都说了要看已关闭议题

**Comment by SherkeyXD** [comment]
能不能速发一个新的内测版覆盖了）
