### ISSUE TITLE
5.9.0 在从旧版本进行版本更新，或复制旧版本config后，启动即闪退

### ISSUE THREAD

**Issue by Starseeker-H** [MaaAssistantArknights/MaaAssistantArknights#11047]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

进行一个超快的bug的报（

应该是config里某些东西和新版本不适配，新版本的包单独解压没问题，config复制过去就打开直接闪退

实测了一下把GUI.json的 ```"Roguelike.Difficulty": "MAX",```全删了就不闪退了，然后再看GUI.json发现```16点```这个配置里又自动出现了 ```"Roguelike.Difficulty": "MAX",```

嗯，不懂（

```
MAA 遇到了问题
	The input string 'MAX' was not in a correct format.
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.FormatException: The input string 'MAX' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Convert.ToInt32(String value)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Version

Resource Version: 揭幕者们
Resource Time: 2024/11/2 23:42:13
UI Version: v5.9.0
Core Version: v5.9.0
Build Time: 2024/11/3 22:22:21

### 日志和配置文件

报错的
[asst.log](https://github.com/user-attachments/files/17610893/asst.log)
[gui.log](https://github.com/user-attachments/files/1761
[gui.json](https://github.com/user-attachments/files/17610896/gui.json)
0894/gui.log)

改后的
[asst.log](https://github.com/user-attachments/files/17610897/asst.log)
[gui.log](https://github.com/user-attachments/files/17610898/gui.log)
[gui.json](https://github.com/user-attachments/files/17610899/gui.json)

### 配置信息

win10, mumu12

**Comment by status102** [comment]
Duplicate of #10998

**Comment by Starseeker-H** [comment]
> Duplicate of #10998

！对不起忘了瞅一眼已关闭……
