### ISSUE TITLE
更新5.9.0之后启动报错

### ISSUE THREAD

**Issue by Kaze-maru** [MaaAssistantArknights/MaaAssistantArknights#11050]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
	The input string 'MAX' was not in a correct format.
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.FormatException: The input string 'MAX' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Convert.ToInt32(String value)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

MAA-v5.9.0-win-x64

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/17612627/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/17612629/asst.log)
[gui.log](https://github.com/user-attachments/files/17612630/gui.log)
[gui.json](https://github.com/user-attachments/files/17612644/gui.json)

### 配置信息

MuMu 12

### 还有别的吗？

常见问题里的两个运行库均已安装，之前5.8.1版本使用没有问题，自动更新至5.9.0后启动如下报错。

--------------------------
MAA 遇到了问题
	The input string 'MAX' was not in a correct format.
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.FormatException: The input string 'MAX' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Convert.ToInt32(String value)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Kaze-maru** [comment]
我的问题...已经有重复issue了不好意思
