### ISSUE TITLE
自动更新后报错，出现未知错误

### ISSUE THREAD

**Issue by Ciallooooo** [MaaAssistantArknights/MaaAssistantArknights#11141]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

2024.11.13半夜0：30左右内测版本自动更新最新版本后报错

### Version

报错无法打开MAA，因此无法获取

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17719885/asst.log)
[gui.log](https://github.com/user-attachments/files/17719900/gui.log)
[asst.bak.log](https://github.com/user-attachments/files/17719902/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/17720025/gui.json)

### 配置信息

win11专业版

### 截图或录屏

![屏幕截图 2024-11-13 004850](https://github.com/user-attachments/assets/be08ca95-1100-4b33-b890-8f3302cf2a1c)

### 还有别的吗？

MAA 遇到了问题
	A valid active Window is needed to update the Taskbar.
解决方案
	出现未知错误
详细信息
System.InvalidOperationException: A valid active Window is needed to update the Taskbar.
   at Microsoft.WindowsAPICodePack.Taskbar.TaskbarManager.get_OwnerHandle()
   at Microsoft.WindowsAPICodePack.Taskbar.TaskbarManager.SetProgressValue(Int32 currentValue, Nullable`1 maximumValue)
   at MaaWpfGui.ViewModels.UI.RootViewModel.set_TaskProgress(Nullable`1 value)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.UpdateMainTasksProgress(Nullable`1 completedCount)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.set_Idle(Boolean value)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.RunningState_IdleChanged(Object sender, Boolean e)
   at MaaWpfGui.States.RunningState.OnIdleChanged(Boolean newIdleValue)
   at MaaWpfGui.States.RunningState.set_Idle(Boolean value)
   at MaaWpfGui.States.RunningState.SetIdle(Boolean idle)
   at MaaWpfGui.Main.AsstProxy.Init()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.RootViewModel.InitProxy()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
[MAA-v5.9.1-alpha.1.d067.gffa7ce55e-win-x64.zip](https://github.com/MaaAssistantArknights/MaaRelease/releases/download/v5.9.1-alpha.1.d067.gffa7ce55e/MAA-v5.9.1-alpha.1.d067.gffa7ce55e-win-x64.zip) fixed
