### ISSUE TITLE
maa 개발버전 오류 발생

### ISSUE THREAD

**Issue by xczsonn** [MaaAssistantArknights/MaaAssistantArknights#11174]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

MAA에서 오류가 발생했습니다
	Object reference not set to an instance of an object.
해결 방법
	FAQ 문서의 크래시 관련 문단을 참고하세요.
세부 정보
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaaWpfGui.ViewModels.UserControl.Settings.GUISettingsUserControlModel.get_OperNameLocalization()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.UpdateRoguelikeCoreCharList()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.InitRoguelike()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.Init()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

확인 불가

### Log and config files

[gui.json](https://github.com/user-attachments/files/17789561/gui.json)
[gui.log](https://github.com/user-attachments/files/17789562/gui.log)

### Configuration information

ld플레이어

**Comment by ABA2396** [comment]
[5.10.1](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.10.1) fixed
