### ISSUE TITLE
MAA遇到了问题：动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by ZhaohuiJiang** [MaaAssistantArknights/MaaAssistantArknights#11198]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

已经在终端中运行以下命令winget install Microsoft.VCRedist.2015+.x64 Microsoft.DotNet.DesktopRuntime.8
MAA 遇到了问题
	Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method27(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

5.10.2.0

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/17817319/asst.log)
[gui.log](https://github.com/user-attachments/files/17817334/gui.log)

今天出的问题，之前也出现过，安装winget install Microsoft.VCRedist.2015+.x64 Microsoft.DotNet.DesktopRuntime.8后修复了，今天又出现了。

### 配置信息

雷电9，分辨率1600*900，没有开启GPU加速推理。

**Comment by ZhaohuiJiang** [comment]
卸载Microsoft.VCRedist.2015+.x64 Microsoft.DotNet.DesktopRuntime.8后重新安装就可以了。
