### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by junjian147159** [MaaAssistantArknights/MaaAssistantArknights#11313]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
	Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method27(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

v5.10.22

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/18050624/gui.json)
[gui.log](https://github.com/user-attachments/files/18050625/gui.log)

### 配置信息

win11 24H2

### 截图或录屏

![image](https://github.com/user-attachments/assets/3e8a2bfb-84ec-4af1-a179-495149e97485)

**Comment by junjian147159** [comment]
缺少运行库

**Comment by status102** [comment]
参照用户手册-新手上路 安装Microsoft.VCRedist.2015+.x64和Microsoft.DotNet.DesktopRuntime.8

**Comment by zongchengLi** [comment]
我这边也是，Win11 从 23H2 更新至 24H2 之后，MAA 就不行了，即使重装 `Microsoft.VCRedist.2015+.x64` 和 `Microsoft.DotNet.DesktopRuntime.8` 也启动不了。

**Comment by Saratoga-Official** [comment]
> 我这边也是，Win11 从 23H2 更新至 24H2 之后，MAA 就不行了，即使重装 `Microsoft.VCRedist.2015+.x64` 和 `Microsoft.DotNet.DesktopRuntime.8` 也启动不了。

把电脑里的VC都卸载了然后再重装就行了
