### ISSUE TITLE
自动更新后MAA无法找到MaaCore.dll

### ISSUE THREAD

**Issue by Zix0722** [MaaAssistantArknights/MaaAssistantArknights#11339]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I am using the latest version of the current update and have reviewed both the updates released so far and the unreleased changes in the Pull Requests, there is no mention of the bug being fixed.
- [X] I have reviewed the Pinned issue (Announcements), Open issues, and Closed issues to ensure that my issue has not been mentioned.

### Description

Details
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method27(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

win11最新系统；
VCRedist & .NET 8 都以更新至最新；
尝试解决方案
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3083#issuecomment-1356318649
无效

### Version

5.10.2.0

### Log and config files

[gui.json](https://github.com/user-attachments/files/18085318/gui.json)
[gui.log](https://github.com/user-attachments/files/18085320/gui.log)

### Configuration information

Edition	Windows 11 Pro
Version	23H2
Installed on	‎9/‎20/‎2022
OS build	22631.4541
Serial number	PF3NSHSX
Experience	Windows Feature Experience Pack 1000.22700.1055.0

### Anthing else?

12月9号还正常，没更新或重装过任何驱动或系统在报错发生之前。

**Comment by Daydreamer114** [comment]
看一眼刚关的issue，解决不了找用户群
