### ISSUE TITLE
启动即报错

### ISSUE THREAD

**Issue by Boss1412** [MaaAssistantArknights/MaaAssistantArknights#11337]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
	Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method27(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

公测版最新

### 日志和配置文件

[asst.log](https://github.com/user-attachments/files/18079442/asst.log)
[asst.bak.log](https://github.com/user-attachments/files/18079443/asst.bak.log)
[gui.bak.log](https://github.com/user-attachments/files/18079445/gui.bak.log)
[gui.json](https://github.com/user-attachments/files/18079448/gui.json)
[asst.log](https://github.com/user-attachments/files/18079452/asst.log)
[gui.log](https://github.com/user-attachments/files/18079456/gui.log)
[gui.bak.log](https://github.com/user-attachments/files/18079460/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/18079471/gui.log)

### 配置信息

MUMU12 未开启截图增强

**Comment by Saratoga-Official** [comment]
提issue之前翻一下关闭的issue，里面解决方法说的很明白了

**Comment by Boss1412** [comment]
> 提issue之前翻一下关闭的issue，里面解决方法说的很明白了

已经尝试安装最新的库了，但是并没有解决问题，依然无法启动

**Comment by Saratoga-Official** [comment]
> > 提issue之前翻一下关闭的issue，里面解决方法说的很明白了
> 
> 已经尝试安装最新的库了，但是并没有解决问题，依然无法启动

你进控制面板程序里面找一下你之前安装过的vc，要么右键然后点一下修复，要么把他们都卸了再重新装，就好了
