### ISSUE TITLE
maa闪退，更新运行库或重新下载maa均失败

### ISSUE THREAD

**Issue by macrolide0** [MaaAssistantArknights/MaaAssistantArknights#11335]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
	Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method27(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

闪退后无法阅读版本。同时在release中的最新版有同样的问题。

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/18070672/asst.bak.log)
[asst.log](https://github.com/user-attachments/files/18070676/asst.log)
[gui.log](https://github.com/user-attachments/files/18070677/gui.log)
[gui.json](https://github.com/user-attachments/files/18070678/gui.json)

### 配置信息

win11 23H2 22631.4541
蓝叠模拟器

**Comment by macrolide0** [comment]
新增：回滚至5.4.0版本可正常启动，触发自动更新至5.10.x（没看清）版本之后再次暴毙

**Comment by macrolide0** [comment]
接上测试，经不懈努力，回滚至5.7.0即不闪退

**Comment by sanguinesmile** [comment]
确认，本人也遇到了一样的问题。

MAA has encountered an error
	Unable to load DLL 'MaaCore.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
Solution
	Please refer to the documentation: 「FAQ - Crashes」 to solve.
Details
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method27(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[gui.log](https://github.com/user-attachments/files/18071087/gui.log)

**Comment by Remilia1023** [comment]
+1，我也遇到了，并且更新运行库和重下也失败了

**Comment by Saratoga-Official** [comment]
把原来的运行库VC和NET都删了，再重新装就行了

**Comment by vcangfy** [comment]
我遇到同样的问题，问题已解决，执行代码winget install Microsoft.VCRedist.2015+.x64 Microsoft.DotNet.DesktopRuntime.8更新依赖即可
