### ISSUE TITLE
MAA闪退，The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.

### ISSUE THREAD

**Issue by abbaccadd0** [MaaAssistantArknights/MaaAssistantArknights#11340]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

更新MAA至[v5.11.0-beta.1.d024.g11ea7470b](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.11.0-beta.1.d024.g11ea7470b)后闪退，下载完整包运行同样闪退
强制重装两个运行库依然闪退
完整错误信息如下

```
MAA 遇到了问题
	The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
The type initializer for 'MaaWpfGui.ViewModels.UserControl.Settings.GuiSettingsUserControlModel' threw an exception.
Object reference not set to an instance of an object.
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UserControl.Settings.GuiSettingsUserControlModel' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MaaWpfGui.ViewModels.UserControl.Settings.GuiSettingsUserControlModel..ctor()
   at MaaWpfGui.ViewModels.UserControl.Settings.GuiSettingsUserControlModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UserControl.Settings.GuiSettingsUserControlModel.get_Instance()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.get_InfrastTask()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.Init()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Version

v5.11.0-beta.1.d024.g11ea7470b

### 日志和配置文件

[gui.json](https://github.com/user-attachments/files/18087357/gui.json)
[gui.log](https://github.com/user-attachments/files/18087359/gui.log)

### 配置信息

Windows 11+Mumu 12 v4.1.8

**Comment by Saratoga-Official** [comment]
重装运行库前把你电脑原有的运行库全卸载再装

**Comment by Saratoga-Official** [comment]
Duplicate of ＃11335
