### ISSUE TITLE
Windows 11 24H2 更新后无法运行MAA，DLL初始化例程失败

### ISSUE THREAD

**Issue by gerald-liu** [MaaAssistantArknights/MaaAssistantArknights#11369]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

Windows 11 24H2 更新之后无法运行MAA，VCRedist 和 .NET 都已按文档要求更新至最新版本。看到以前issue有说加群，但我申请了一个暂未通过。

![Runtime libraries installed](https://github.com/user-attachments/assets/5de5ed62-8f7e-43ce-94aa-410d2b605d19)

![System version](https://github.com/user-attachments/assets/bbf1778f-c2fc-4841-901e-a9f9b0de06e6)

### Version

从GitHub下载了最新版pre-release并进行文件覆盖，由于无法启动软件，只能这样看版本号：

![MAA version](https://github.com/user-attachments/assets/2da06b06-8bb6-4b0a-bf93-fdcf4cdd752a)

资源版本也是最新的（不过应该跟这个问题无关）：

![maa resource version](https://github.com/user-attachments/assets/1450eb92-01fd-411c-ae3e-05ca9e88b98d)

### 日志和配置文件

因为是全新下载的，debug文件夹中只有 gui.log 一个文件

[gui.log](https://github.com/user-attachments/files/18139324/gui.log)

[gui.json](https://github.com/user-attachments/files/18139332/gui.json)

### 配置信息

Windows 11 24H2 26100.2605
模拟器是蓝叠，不过不重要，现在MAA软件都启动不了

### 截图或录屏

MAA 遇到了问题
	Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method27(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
如果还是加载不了的话，点那个链接进去下一下 vc++ 的安装包，打开之后点那个修复或者卸载后重新安装。
