### ISSUE TITLE
动态链接库(DLL)初始化例程失败

### ISSUE THREAD

**Issue by Agnes4m** [MaaAssistantArknights/MaaAssistantArknights#11383]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

系统windows10 22h2（官方源非三方）
在前一天（12.17日）正常启动，今天打开时报错，已按照文档尝试过以下方式，均失败后提出iss
1、重启电脑
2、重装net8.0
3、重新下载maa文件（res里5.10.2）覆盖原文件启动
4、把重新下载的res里的5.10.2版本直接启动（同样的报错）
5、dll和注册表修复工具

### Version

昨天我记得更新到5.11.0b吧，现在打不开不清楚，重新下载的版本是res的5.10.2

### 日志和配置文件

[asst.bak.log](https://github.com/user-attachments/files/18176864/asst.bak.log)
[gui.json](https://github.com/user-attachments/files/18176872/gui.json)
[gui.bak.log](https://github.com/user-attachments/files/18176875/gui.bak.log)
[gui.log](https://github.com/user-attachments/files/18176884/gui.log)
[asst.log](https://github.com/user-attachments/files/18176874/asst.log)
gui最后位置，15点后

### 配置信息

雷电模拟器9，截图增强未开启
1280*720
60帧
GPU使用inter核显

### 截图或录屏

MAA 遇到了问题
	The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
The type initializer for 'MaaWpfGui.ViewModels.UserControl.Settings.VersionUpdateSettingsUserControlModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
解决方案
	请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UserControl.Settings.VersionUpdateSettingsUserControlModel' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UserControl.Settings.VersionUpdateSettingsUserControlModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UserControl.Settings.VersionUpdateSettingsUserControlModel.get_Instance()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.get_InfrastTask()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.Init()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Agnes4m** [comment]
刚刚尝试了更VS为最新版本，依旧无法成功启动，报错是一样的
![image](https://github.com/user-attachments/assets/ce43d631-94a1-437c-9953-15fb7ea201bc)

**Comment by ABA2396** [comment]
这个报错就是 vc++ 的版本不对，常见问题点进去，下 vc++ 的运行库安装包，点修复或者卸载后重新安装

**Comment by Agnes4m** [comment]
> 这个报错就是 vc++ 的版本不对，常见问题点进去，下 vc++ 的运行库安装包，点修复或者卸载后重新安装

我在提出iss前已经点击**常见问题**，并且使用以下指令安装过，无法解决问题

```base
winget install Microsoft.VCRedist.2015+.x64 Microsoft.DotNet.DesktopRuntime.8
```

按说法我在应用管理里找到对应的c++运行库手动修复，解决问题
![image](https://github.com/user-attachments/assets/df59a61e-4957-4d0d-975b-d2fd2385f251)

**Comment by Saratoga-Official** [comment]
这个解决方法我在之前的issue就说过了，不开之前issue就提是吧，在提问之前...的四个选项是摆设吗
