### ISSUE TITLE
无法用命令行启动MAA.exe

### ISSUE THREAD

**Issue by nishiki066** [MaaAssistantArknights/MaaAssistantArknights#11440]
> [!warning]
存在未确认的链接，请谨慎访问。
There are unconfirmed links, please visit with caution.

### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我使用的是当前更新版本的最新版，且已查看版本发布至今和 Pull Requests 中尚未发布的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（Pinned Issue）（公告）、活跃议题（Open Issue）、已关闭议题（Closed Issue），确认我的问题未被提及

### 问题描述

MAA 无法用命令行启动
平时是通过命令行启动maa 和模拟器的
【这个是我启动maa和模拟器的大致过程】
[23:41:38] 脚本状态已插入数据库，开始执行 arkcn.py...
Connected (version 2.0, client OpenSSH_for_Windows_9.5)
Authentication (publickey) failed.
Authentication (password) successful!
[23:41:41] 正在查询用户 ark 的会话信息...
[23:41:41] 未找到用户 ark 的符合条件的会话。
[23:41:41] 正在检查可用的虚拟显示器编号...
[23:41:41] 选择的虚拟显示器编号为 :114
[23:41:41] 启动虚拟显示器 Xvfb...
[23:41:46] 虚拟显示器启动成功 (PID: 1103521)
[23:41:46] 设置 DISPLAY 环境变量为 ::114
[23:41:46] 启动 RDP 会话...
[23:41:56] RDP 会话启动成功 (PID: 1103553)，正在检查远程主机上的会话...
[23:41:56] 正在查询用户 ark 的会话信息...
[23:41:57] 用户 ark 的会话 0 包含 rdp-tcp，RDP 会话已成功建立。
[23:41:57] RDP 会话成功启动，继续执行模拟器启动...
[23:41:57] 清理中...
[23:41:57] 发送关闭 Mumu 模拟器指令。
[23:41:58] 发送关闭 Maa指令
[23:41:58] 正在启动 第一个 Mumu 模拟器，脚本路径: C:\Users\zheng\Desktop\arkre\run_task_mumu.py
[23:42:33] 第一个 Mumu 模拟器 等待20秒启动mumu模拟器。
[23:43:51] 第一个 Mumu 模拟器 等待20秒启动mumu模拟器。
[23:43:57] 第一个 Mumu 模拟器 启动成功。
[23:43:57] 正在启动 MAA 159...
[23:44:08] [2J[m[H[启动] 启动: C:\Users\zheng\Desktop\maa cn\MAA.exe
【这个是我启动maa和模拟器的大致过程】

然后卡在了这一边
我去检查了下gui.log文件

发现了下面这些

[2024-12-27 22:43:59.772][INF] <1><> ===================================
[2024-12-27 22:43:59.793][INF] <1><> MaaAssistantArknights GUI started
[2024-12-27 22:43:59.794][INF] <1><> Version v5.11.0
[2024-12-27 22:43:59.795][INF] <1><> Built at 2024-12-26T23:19:22.2548133+08:00
[2024-12-27 22:43:59.796][INF] <1><> Maa ENV: Production
[2024-12-27 22:43:59.796][INF] <1><> Command Line: C:\Users\zheng\Desktop\maa cn\MAA.exe
[2024-12-27 22:43:59.796][INF] <1><> User Dir C:\Users\zheng\Desktop\maa cn
[2024-12-27 22:43:59.799][INF] <1><> Run as Administrator
[2024-12-27 22:43:59.799][INF] <1><> ===================================
[2024-12-27 22:44:00.815][ERR] <1><> Failed to set startup: No value exists with that name.
[2024-12-27 22:44:00.904][ERR] <1><> Failed to decrypt text: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
[2024-12-27 22:44:05.334][FTL] <1><> Unhandled exception occurred
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Windows.Markup.XamlParseException: “对类型“MaaWpfGui.Views.UI.NotifyIcon”的构造函数执行符合指定的绑定约束的调用时引发了异常。”，行号为“55”，行位置为“10”。
 ---> System.ArgumentException: Invalid value '0' for parameter 'interval'.
   at System.Timers.Timer..ctor(Double interval)
   at MaaWpfGui.Views.UI.NotifyIcon..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at MaaWpfGui.Views.UI.RootView.InitializeComponent()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Stylet.ViewManager.InitializeView(UIElement view, Type viewType)
   at Stylet.ViewManager.CreateViewForModel(Object model)
   at Stylet.ViewManager.CreateAndBindViewForModel(Object model)
   at Stylet.ViewManager.CreateAndBindViewForModelIfNecessary(Object model)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at MaaWpfGui.Helper.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at MaaWpfGui.Main.Bootstrapper.DisplayRootView(Object rootViewModel)
   at Stylet.Bootstrapper`1.Launch()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

针对这些maa异常错误信息，目前不知道是怎么产生的。

之前的话，在maa没版本更新之前，是能通过我刚才说的那个方式启动maa的。

# 路径设置
maa_159_path = r"C:\Users\zheng\Desktop\maa cn\MAA.exe"
maa_159_log_file_path = r"C:\Users\zheng\Desktop\maa cn\debug\gui.log"
 """
    启动 MAA 应用程序并监控任务进度
    :param app_path: MAA 应用程序的路径
    :param log_file_path: 日志文件的路径
    """
    process_name = os.path.basename(app_path)
    
    # 启动应用程序
    print(f"[启动] 启动: {app_path}")
    process = subprocess.Popen(app_path, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, text=True, shell=True)
    
    # 启动日志监控线程
    log_monitor_thread = threading.Thread(target=monitor_log_file, args=(log_file_path, process), daemon=True)
    log_monitor_thread.start()
    
    # 等待任务完成
    while process.poll() is None:  # 如果 MAA 程序仍在运行
        time.sleep(1)
    
    print(f"[结束] 结束: {app_path}, 任务已完成。")

### Version

Version v5.11.0

### 日志和配置文件

[debug.zip](https://github.com/user-attachments/files/18261196/debug.zip)

### 配置信息

Windows 10 专业版22H2   19045.5247

MuMuEmulator12

**Comment by nishiki066** [comment]
我不知道说[无法用命令行启动MAA.exe]这个说法准不准确。
因为我是先发起rdp会话， 然后用上述的命令行启动maa的

如果是手动，也就是我通过rdp远程上去，用鼠标去点启动maa的脚本，是可以启动maa
