### ISSUE TITLE
稳定版导航和唤醒仍未更新，开发版python调用出现问题

### ISSUE THREAD

**Issue by ChildeRolando** [MaaAssistantArknights/MaaAssistantArknights#2996]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，且会尽可能提供更多信息帮助问题解决
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的常见问题、详细使用说明等，认为这大概率是一个 bug 而非设计如此
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我上传的游戏画面截图是模拟器自带的截图工具（或通过 adb）截取的原图

### 问题描述

1.稳定版无法对风雪过境关卡寻址。
2.稳定版会卡在开屏，最后一个公告窗口一直不点掉导致卡住。

开发版python接口突然出问题：
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\Code\python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "F:\Code\python\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".\MAA1.py", line 201, in job
    routine(dllPath, adbPath, accountPath, noxPath)
  File ".\MAA1.py", line 80, in routine
    Asst.load(dllPath)
  File "E:\桌面\G\MeoAssistantArknights\Python\asst.py", line 38, in load
    Asst.__lib = ctypes.WinDLL(str(Asst.__libpath))
  File "F:\Code\python\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。`

### 日志文件

无

**Comment by horror-proton** [comment]
相关问题 
- https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1937

**Comment by ChildeRolando** [comment]
已解决
