### ISSUE TITLE
更新后无法启动

### ISSUE THREAD

**Issue by lotusia12** [MaaAssistantArknights/MaaAssistantArknights#3081]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

今天更新后无法启动了， 以下为 error 和 details

  Unable to load DLL 'MeoAssistant.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   at MeoAsstGui.VersionUpdateViewModel.AsstGetVersion()
   at MeoAsstGui.VersionUpdateViewModel..ctor(IContainer container, IWindowManager windowManager)
   at lambda_method(Closure , IRegistrationContext )
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MeoAsstGui.RootViewModel.CheckAndUpdateNow()
   at MeoAsstGui.RootViewModel.OnViewLoaded()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

以下为今天的log：
[2022-12-15 18:24:17.123][TRC][Px3bc4][Tx3a20] -----------------------------
[2022-12-15 18:24:17.138][TRC][Px3bc4][Tx3a20] MeoAssistant Process Start
[2022-12-15 18:24:17.138][TRC][Px3bc4][Tx3a20] Version v4.7.3
[2022-12-15 18:24:17.138][TRC][Px3bc4][Tx3a20] Built at Nov 28 2022 16:07:54
[2022-12-15 18:24:17.138][TRC][Px3bc4][Tx3a20] User Dir C:\Users\lotus\Desktop\maa
[2022-12-15 18:24:17.138][TRC][Px3bc4][Tx3a20] -----------------------------
[2022-12-15 18:24:17.138][TRC][Px3bc4][Tx3a20] asst::ResourceLoader::load | enter
[2022-12-15 18:24:17.138][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet GeneralConfiger | enter
[2022-12-15 18:24:17.138][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | enter
[2022-12-15 18:24:17.138][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\config.json
[2022-12-15 18:24:17.938][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | leave, 800 ms
[2022-12-15 18:24:17.939][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet GeneralConfiger | leave, 800 ms
[2022-12-15 18:24:17.939][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet RecruitConfiger | enter
[2022-12-15 18:24:17.939][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | enter
[2022-12-15 18:24:17.939][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\recruitment.json
[2022-12-15 18:24:18.051][TRC][Px3bc4][Tx3a20] asst::RecruitConfiger::clear | enter
[2022-12-15 18:24:18.054][TRC][Px3bc4][Tx3a20] asst::RecruitConfiger::clear | leave, 2 ms
[2022-12-15 18:24:18.054][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | leave, 114 ms
[2022-12-15 18:24:18.054][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet RecruitConfiger | leave, 114 ms
[2022-12-15 18:24:18.054][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet StageDropsConfiger | enter
[2022-12-15 18:24:18.054][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | enter
[2022-12-15 18:24:18.054][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\stages.json
[2022-12-15 18:24:18.422][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | leave, 368 ms
[2022-12-15 18:24:18.422][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet StageDropsConfiger | leave, 368 ms
[2022-12-15 18:24:18.423][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet RoguelikeCopilotConfiger | enter
[2022-12-15 18:24:18.446][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | enter
[2022-12-15 18:24:18.446][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\roguelike_copilot.json
[2022-12-15 18:24:18.479][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | leave, 33 ms
[2022-12-15 18:24:18.479][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet RoguelikeCopilotConfiger | leave, 57 ms
[2022-12-15 18:24:18.479][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet RoguelikeRecruitConfiger | enter
[2022-12-15 18:24:18.479][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | enter
[2022-12-15 18:24:18.479][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\roguelike_recruit.json
[2022-12-15 18:24:18.518][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | leave, 38 ms
[2022-12-15 18:24:18.518][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet RoguelikeRecruitConfiger | leave, 38 ms
[2022-12-15 18:24:18.518][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet RoguelikeShoppingConfiger | enter
[2022-12-15 18:24:18.518][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | enter
[2022-12-15 18:24:18.518][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\roguelike_shopping.json
[2022-12-15 18:24:18.552][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | leave, 33 ms
[2022-12-15 18:24:18.552][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet RoguelikeShoppingConfiger | leave, 34 ms
[2022-12-15 18:24:18.552][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet BattleDataConfiger | enter
[2022-12-15 18:24:18.552][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | enter
[2022-12-15 18:24:18.552][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\battle_data.json
[2022-12-15 18:24:18.617][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | leave, 64 ms
[2022-12-15 18:24:18.617][TRC][Px3bc4][Tx3a20] LoadResourceAndCheckRet BattleDataConfiger | leave, 64 ms
[2022-12-15 18:24:18.617][TRC][Px3bc4][Tx3a20] LoadResourceWithTemplAndCheckRet TaskData | enter
[2022-12-15 18:24:18.617][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | enter
[2022-12-15 18:24:18.617][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\tasks.json
[2022-12-15 18:24:18.672][TRC][Px3bc4][Tx3a20] asst::TaskData::parse | enter
[2022-12-15 18:24:18.699][TRC][Px3bc4][Tx3a20] asst::TaskData::parse | leave, 26 ms
[2022-12-15 18:24:18.699][TRC][Px3bc4][Tx3a20] asst::AbstractConfiger::load | leave, 81 ms
[2022-12-15 18:24:18.699][TRC][Px3bc4][Tx3a20] asst::TemplResource::load | enter
[2022-12-15 18:24:18.699][INF][Px3bc4][Tx3a20] load C:\Users\lotus\Desktop\maa\resource\template

### 还有别的吗？

使用的是bluestack模拟器。

**Comment by 1killer10** [comment]
12月十六日上午八点，我更新过后出现了相同的问题

**Comment by 1killer10** [comment]
找到了解决办法，去安装目录里找到MAA.exe打开而非MeoAsstGui.exe

**Comment by lotusia12** [comment]
解决了，谢谢！ @1killer10
