### ISSUE TITLE
出现未知错误Could not load type 'System.ValueTuple`2' from assembly 'mscorlib

### ISSUE THREAD

**Issue by lxyddice** [MaaAssistantArknights/MaaAssistantArknights#3272]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral

at MaaWpfGui.VersionUpdateViewModel.CheckAndDownloadUpdate(Boolean force)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.RootViewModel.<ShowUpdateOrDownload>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10334448/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10334453/gui.log)

### 截图

![Snipaste_2023-01-03_13-27-39](https://user-images.githubusercontent.com/95132858/210304482-c0ee151e-44f6-4f37-bdef-5fc290172375.png)

**Comment by WWPXX233** [comment]
[Sample.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10350334/Sample.zip)
把这个解压缩以后放在maa目录里 运行查看结果
