### ISSUE TITLE
Maa启动错误

### ISSUE THREAD

**Issue by oiy452** [MaaAssistantArknights/MaaAssistantArknights#3321]
### 说说你遇到的问题？

Maa启动错误，无法加载DLL”MaaCore.dll"，找不到指定模块
![IMG_20230109_172722](https://user-images.githubusercontent.com/122266451/211282477-6785a7b6-6a5b-4349-b3ba-81d0d3e6c973.jpg)

**Comment by MistEO** [comment]
方案都尝试了？

**Comment by loinway** [comment]
相同问题，操作：
1. 4.7.3正常使用，自动升级失败
2. 手动下载4.9.1，保留gui.json，打开有此弹窗
3. 常见问题种提到的所有库均正常

**Comment by MistEO** [comment]
[win10rt.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10394075/win10rt.zip)

解压塞到 MAA 目录下试试

**Comment by loinway** [comment]
解压后亦无区别，附报错
   at MaaWpfGui.VersionUpdateViewModel.AsstGetVersion()
   at MaaWpfGui.VersionUpdateViewModel..ctor(IContainer container, IWindowManager windowManager)
   at lambda_method(Closure , IRegistrationContext )
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.RootViewModel.CheckAndUpdateNow()
   at MaaWpfGui.RootViewModel.OnViewLoaded()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
