### ISSUE TITLE
NullReferenceException from MaaWpfGui.SettingsViewModel when starting

### ISSUE THREAD

**Issue by Iamanorange** [MaaAssistantArknights/MaaAssistantArknights#3687]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

v4.10.8-beta.1

Let's Start 之后报了个NPE，看起来是UI上报的。

2023-02-13 23:54:57 

2023-02-13 23:54:57 正在连接模拟器……
2023-02-13 23:55:00 OnUnhandledException Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at MaaWpfGui.SettingsViewModel.get_CreditFightTaskEnabled()
   at MaaWpfGui.TaskQueueViewModel.appendMall()
   at MaaWpfGui.TaskQueueViewModel.<LinkStart>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[debug.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10723913/debug.zip)

### 截图

<img width="876" alt="image" src="https://user-images.githubusercontent.com/6018925/218508302-702f4fa6-e716-430c-8ddc-87b93a4c369f.png">

**Comment by Iamanorange** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/2133e2560a12d2396a2605f6bb0829be711d101a
Suspicious commit.

**Comment by ChingCdesu** [comment]
晚上我尝试修复
