### ISSUE TITLE
MAA crashes when GUI language is set to 日本語 (Japanese)

### ISSUE THREAD

**Issue by Lysozyme** [MaaAssistantArknights/MaaAssistantArknights#3831]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

1. Delete the `config` folder to reset settings
2. Open MAA
3. Set `Settings` > `GUI` > `Language` to `日本語`
4. Close MAA
5. Open MAA
6. Error dialog is shown, and MAA does not open

```
Error
Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.

Solution
Unknown error occurred

Details
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at MS.Internal.AppModel.AppModelKnownContentFactory.BamlConverter(Stream stream, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStream(Stream s, ContentType contentType, Uri baseUri, Boolean canUseTopLevelBrowser, Boolean sandboxExternalContent, Boolean allowAsync, Boolean isJournalNavigation, XamlReader& asyncObjectConverter)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at MaaWpfGui.Localization.Load()
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Log files

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10833409/gui.log)

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10833408/asst.log)

### Screenshots

![20230226_185407](https://user-images.githubusercontent.com/60739916/221403728-167504e3-a1a2-40f8-b6b1-72ff2af4d063.png)

### Anthing else?

In step 3, if I change to any language other than Japanese, the `the language setting has been changed, restart the app now?` dialog appears, and the language is properly changed upon restart.
However, only when changing to Japanese, this dialog itself does not appear, so I must restart MAA manually.
I am on Windows 11 Pro English version.

**Comment by ABA2396** [comment]
You can refer to #3805, and this problem in the distribution will be solved after the next version is updated.
