### ISSUE TITLE
MAA遇到未知错误（无法启动）

### ISSUE THREAD

**Issue by Dulax0201** [MaaAssistantArknights/MaaAssistantArknights#4585]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

我下载安装了[MAA-v4.16.0-win-x64.zip]版本https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.16.0/MAA-v4.16.0-win-x64.zip)，启动后显示“出现未知错误”，重复启动数次无法解决，错误信息如下：
MAA has encountered an error
External component has thrown an exception.
Solution
Unknown error occurred
Details
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Main.AsstProxy.AsstLoadResource(Byte* dirname)
   at MaaWpfGui.Main.AsstProxy.AsstLoadResource(String dirname)
   at MaaWpfGui.Main.AsstProxy.LoadResource()
   at MaaWpfGui.Main.AsstProxy.Init()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.ViewModels.UI.RootViewModel.<InitProxy>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

MAA has encountered an error
External component has thrown an exception.
Solution
Unknown error occurred
Details
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Main.AsstProxy.AsstLoadResource(Byte* dirname)
   at MaaWpfGui.Main.AsstProxy.AsstLoadResource(String dirname)
   at MaaWpfGui.Main.AsstProxy.LoadResource()
   at MaaWpfGui.Main.AsstProxy.Init()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.ViewModels.UI.RootViewModel.<InitProxy>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 截图

<img width="450" alt="1682951998256" src="https://user-images.githubusercontent.com/129756556/235469358-5401f4b7-5cc2-47e5-85d7-ef3f17ff1f30.png">

### 还有别的吗？

使用蓝叠模拟器国际版，系统为win10

**Comment by MistEO** [comment]
debug 文件夹下的几个 log 文件发下看看

**Comment by Dulax0201** [comment]
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11366240/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/11366241/asst.log)

**Comment by MistEO** [comment]
中文目录出问题了，先不要放在中文目录，试试看。之后版本会修掉

**Comment by Dulax0201** [comment]
换了个安装目录，现在解决了
