### ISSUE TITLE
Latest alpha version makes maa unable to open with error corde

### ISSUE THREAD

**Issue by whayatosan** [MaaAssistantArknights/MaaAssistantArknights#5671]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

MAA fails to open after updating to latest alpha.

### Log files

MAA has encountered an error
No matching constructor found on type 'System.String'. You can use the Arguments or FactoryMethod directives to construct this type.
No default constructor found for type 'System.String'. You can use the Arguments or FactoryMethod directives to construct this type.
Solution
Please refer to the documentation: 「FAQ - Crashes」 to solve.
Details
System.Windows.Markup.XamlParseException: No matching constructor found on type 'System.String'. You can use the Arguments or FactoryMethod directives to construct this type. ---> System.MissingMethodException: No default constructor found for type 'System.String'. You can use the Arguments or FactoryMethod directives to construct this type.
   at System.Xaml.Schema.XamlTypeInvoker.DefaultCtorXamlActivator.EnsureConstructorDelegate(XamlTypeInvoker type)
   at System.Xaml.Schema.XamlTypeInvoker.DefaultCtorXamlActivator.CreateInstance(XamlTypeInvoker type)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at System.Windows.Baml2006.WpfKnownTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at MaaWpfGui.Helper.LocalizationHelper.GetString(String key, String culture)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.InfrastInit()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method(Closure , IRegistrationContext )
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Screenshots

none. please refer to log.

### Anthing else?

OS: Windows 11

**Comment by ABA2396** [comment]
I found the problem, but you'll have to reinstall the full package to fix it, now you'd better want to return to the previous version

**Comment by ABA2396** [comment]
[v4.20.1-alpha.1.d019.g0a58b23d7](https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v4.20.1-alpha.1.d019.g0a58b23d7)

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/5ca43667-406f-4e4f-9502-c9254231c454)

**Comment by whayatosan** [comment]
Thanks for the quick repair.
