### ISSUE TITLE
最新内测版本报错 | v4.24.1-alpha.1.d143.g45edba113 ERROR

### ISSUE THREAD

**Issue by HeartyYF** [MaaAssistantArknights/MaaAssistantArknights#6610]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

如题，更新到v4.24.1-alpha.1.d143.g45edba113后只要尝试打开就直接崩溃

### 日志文件

config文件：
[gui.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12776735/gui.zip)
日志：
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12776739/gui.log)

### 还有别的吗？

尝试过删掉config并让它自己生成一个新的，也直接崩溃

**Comment by Constrat** [comment]
```
MAA has encountered an error
The type initializer for 'MaaWpfGui.Configuration.ConfigFactory' threw an exception.
Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Solution
Please refer to the documentation: 「FAQ - Crashes」 to solve.
Details
System.TypeInitializationException: The type initializer for 'MaaWpfGui.Configuration.ConfigFactory' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at ObservableCollections.ObservableDictionary`2.set_Item(TKey key, TValue value)
   at MaaWpfGui.Configuration.RootConfig.set_CurrentConfig(SpecificConfig value)
   at MaaWpfGui.Configuration.ConfigFactory.<>c.<.cctor>b__18_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at MaaWpfGui.Configuration.ConfigFactory..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.SwitchDarkMode()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method(Closure , IRegistrationContext )
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```
@Lancarus Latest action/nightly

**Comment by status102** [comment]
#6617 那边还传了asst.log

**Comment by Constrat** [comment]
> #6617 那边还传了asst.log

Pretty sure it's the same for everyone that updates as it seems to be a core change.

**Comment by zzyyyl** [comment]
cafab39ddc6b691dc3e18830b55eb81f014a8484

**Comment by zzyyyl** [comment]
A new nightly version is being packaged, please wait.

**Comment by zzyyyl** [comment]
可以先用 .old/ 文件夹中的文件替换，之后等待更新

**Comment by Constrat** [comment]
Yeah I've already proceeded with that but I stills don't understand why there were so many dll

**Comment by Constrat** [comment]
Btw in the issue template shouldn't we add a "I've checked this is not a duplicate"? I understand wanting to help but we had 6 identical duplicate issues. Managing them is a bit of a hassle.

**Comment by zzyyyl** [comment]
> A new nightly version is being packaged, please wait. 新的内测版正在打包，稍等片刻
> 
> You can replace it with the file in the `.old/` folder and wait for the update. 可以先用 `.old/` 文件夹中的文件替换，之后等待更新

不对劲，现在好像还是不行
我等会儿发个直接 revert 到 v4.24.0 的版本

**Comment by Constrat** [comment]
We waited too long between nightlies. Debugging this'll be a pain

**Comment by Constrat** [comment]
### v4.24.1-alpha.1.d144.g482d175f0 reverted back to 4.24.0. If you don't want to rollback, this will do it automatically.

**Comment by Constrat** [comment]
Let's hope no one'll open new issues.

**Comment by Cryolitia** [comment]
fix in https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/6632

caused by https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/d6d163d9d0dc86fe78a59db85f257c635ca6a1b0#diff-72b586376b5ff32e544e797aadfb80d3db6e9fb76419c77a1cfa89edffa7ca97L2
