### ISSUE TITLE
Windows Defender 误报特洛伊木马 | Trojan False Positive

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#6662]
## 解决方案 | SOLUTION

See https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662#issuecomment-1859202374

### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

I just updated to d183 nightly on my win11 device without issues.
Tried to do the same for my win10 machine and it gave off a Trojan false positive

### Log files

```
MAA has encountered an error
Operation did not complete successfully because the file contains a virus or potentially unwanted software
Solution
Unknown error occurred
Details
System.ComponentModel.Win32Exception (0x80004005): Operation did not complete successfully because the file contains a virus or potentially unwanted software
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   at MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/95993796-7738-47fe-98dd-49d44a3296f3)

**Comment by Constrat** [comment]
@MistEO suggestions?

**Comment by Constrat** [comment]
Will do

________________________________

**Comment by Constrat** [comment]
> Try to report to Microsoft? https://www.microsoft.com/en-us/wdsi/filesubmission

Wait this is more complicated than I expected.

**Comment by SherkeyXD** [comment]
Any updates? Recently more and more people encounter this problem.

**Comment by Constrat** [comment]
I haven't dug in enough. University start has made less time available.

**Comment by Constrat** [comment]
Submitted as a Home customer. Let's see what happens.

**Comment by Constrat** [comment]
Submission details
maa.exe
Submission ID: 8cc232a6-a825-4124-ad0f-fadda58c2387
Status: Completed
Submitted by: `personal e-mail (prefer not to show)`
Submitted: Oct 5, 2023 21:28:17
User Opinion: Incorrect detection

Analyst comments:

We have determined that the files meet our criteria for malware. At this time the detection will remain in place.

More detailed information about the approach and criteria categories currently used by the Microsoft researchers are available here:
https://docs.microsoft.com/windows/security/threat-protection/intelligence/criteria

Thank you for contacting Microsoft.

@SherkeyXD @MistEO

**Comment by SherkeyXD** [comment]
One of us submitted the report as a Software Developer yesterday, and here's the reply.
<img width="848" alt="a3bee597aa12b86168cdd3bd542a5e8b" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57581480/dafcbaad-0a0a-413f-bff7-e83a158bbf0c">
I wonder if this will remove all malware reports for MAA, or just for a specific version?

**Comment by Constrat** [comment]
I can't remember which version I've sent them. Definitely >= d183

**Comment by Constrat** [comment]
I've tried comparing between alphas, but nothing catches my eye.

**Comment by Constrat** [comment]
I can't understand how my submission got denied, while yours got accepted.

**Comment by SherkeyXD** [comment]
> I can't understand how my submission got denied, while yours got accepted.

Maybe reporting as a developer urge them to pay more attention to MAA XD

**Comment by Constrat** [comment]
> Maybe reporting as a developer urge them to pay more attention to MAA XD

You're probably right... But I linked them the Organization page... Maybe mine was bot automated.

**Comment by Constrat** [comment]
I've linked them this https://github.com/MaaAssistantArknights/MaaAssistantArknights

**Comment by Constrat** [comment]
> One of us submitted the report as a Software Developer yesterday, and here's the reply. <img alt="a3bee597aa12b86168cdd3bd542a5e8b" width="848" src="https://user-images.githubusercontent.com/57581480/273294237-dafcbaad-0a0a-413f-bff7-e83a158bbf0c.png"> I wonder if this will remove all malware reports for MAA, or just for a specific version?

Btw, I've tried their suggestions, but the revision number stayed the same lol

**Comment by Constrat** [comment]
I've tried again just now, and `d226` still gets flagged as `Trojan:Win32/Wacatac.H!ml`

**Comment by you9you** [comment]
好像只有maa.exe报毒，我通过AlasMaaBridge使用一切正常

**Comment by Constrat** [comment]
For now the only solution is to bypass the folder where MAA is
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/18421ea0-4f0c-493a-b68c-0ee8c48f2d03)

**Comment by Constrat** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/f17f0a5a-d2c5-49f5-ba22-2d642f109178)
@SherkeyXD This is new... Can't even download the updates manually
I'm downloading manually because ref #6754

**Comment by SherkeyXD** [comment]
According to @dantmnf, this problem might be caused by [Costura.Fody](https://github.com/Fody/Costura).

**Comment by Constrat** [comment]
> @SherkeyXD
> According to @dantmnf, this problem might be caused by [Costura.Fody](https://github.com/Fody/Costura).

 
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/9e5c999f237b721d0711a6c273cede5f5aa5c88b?

**Comment by SherkeyXD** [comment]
This commit tries to disable Costrua when not in `Release` mode to enable debug. The only difference is that the usage of another fody plugin make it impossible to configure fody only by `FodyWeavers.xml`, so I move it inside csproj.
 
Costura's behavior should be the same.

**Comment by SherkeyXD** [comment]
> https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/9e5c999f237b721d0711a6c273cede5f5aa5c88b?
> Time-wise it started happening exactly after this. I didn't give it much thought before

This commit tries to disable Costrua when not in `Release` mode to enable debug. The only difference is that the usage of another fody plugin make it impossible to configure fody only by `FodyWeavers.xml`, so I move it inside csproj.
 
Costura's behavior should be the same.

**Comment by sausagechen** [comment]
As a reminder to the devs, Version v4.24.0 stable exe also appears to be deleted.

**Comment by SchwarzXia** [comment]
目前d063版本依然有这个问题，且被检测为`Behavior:Win32/DefenseEvasion.A!ml`，和之前的不一样

**Comment by ABA2396** [comment]
现在最简单的办法就是装个杀软（比如火绒）把 Windows Defender 给关了）

**Comment by tossking** [comment]
MAA被win10自带的杀软报毒干掉了。

MAA 遇到了问题
Operation did not complete successfully because the file contains a virus or potentially unwanted software
解决方案
出现未知错误
详细信息
System.ComponentModel.Win32Exception (0x80004005): Operation did not complete successfully because the file contains a virus or potentially unwanted software
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   at MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by kayanouriko** [comment]
4.25.0 依旧存在误报.
我的 wd 目前还不会自动删除程序, 在误报后点击通知可以操作手动允许而不是隔离或者删除.
在 maa 解决之前临时方案是: `Windows 安全中心 - 病毒和威胁防护 - "病毒和威胁防护"设置(管理设置) - 排除项(添加或删除排除项) - 添加排除项`, 将 maa 根路径添加进去, 等待 maa 修复.

**Comment by Constrat** [comment]
This has already been said: https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6662#issuecomment-1751981114 if we can stop the spam, people will see it more easily.

### UNLESS YOU HAVE NEW INFORMATIONS DO NOT REPLY

**Comment by Constrat** [comment]
@SherkeyXD maybe let's lock this conversation?

**Comment by SherkeyXD** [comment]
Once I disable Costura.Fody it stops to report decection of virus.

Is there any alternative to it?

**Comment by Constrat** [comment]
> From https://github.com/Fody/Costura

!!! READ THIS !!! Package is in maintenance mode !!! READ THIS !!!
In .NET Core 3 there are two new features:

[Single-file executables](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables)
[Assembly linking](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#assembly-linking)
With these features included in the dotnet tool set, the value proposition of Costura is greatly diminished.

Therefore we strongly recommend to try out the alternatives mentioned above.

[Supported use cases](https://github.com/Fody/Costura#supported-use-cases)
Costura will be kept in maintenance mode for the following use-cases because they are used by the maintainers:

C# projects (we have no experience with VB.NET, nor have any intention supporting this)
Library linking (e.g. embed dependencies in library projects)
Exe linking (e.g. embed dependencies in exe projects)
Windows platforms
Any advanced scenario that you are not willing to contribute (money, PR, etc) after discussing with the core contributes first
[Non-supported use cases](https://github.com/Fody/Costura#non-supported-use-cases)
VB.NET (see above)
Windows Services
Non-Windows platforms
Note that this list may be updated and will become more strict over time.

**Comment by MistEO** [comment]
We plan to upgrade to .NET 8 to disable Costura.Fody, @ABA2396 is following on this. xD

**Comment by zzyyyl** [comment]
话说最近改啥了，怎么突然多了一堆误报的 issue

**Comment by SherkeyXD** [comment]
不懂啊 基本是从 beta2 开始出问题的

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/e29a7cd4-a372-4973-9ad9-273b36ae6e02)
传一份群里的解决方法
