### ISSUE TITLE
Failed to send GET request to https://ota.maa.plus

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#6754]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Since the past 3 days I haven't been able to update via 
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/876999cc-226b-4eef-9c92-0ef49f9175cf)
After clicking `Check update` it greys out and nothing else happens.
[2023-10-08 12:08:21.656] <1><> Failed to send GET request to 
```
"https://ota.maa.plus/MaaAssistantArknights/api/version/summary.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:08:36.671] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/overview.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
```

Went to gui.log to check if something was wrong and I found something else that could be related.
Am I the only one that has been getting this?

### Log files
Maybe related
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/6446935576/job/17502682412
<details><summary>Log</summary>
<p>

```
[2023-10-08 12:01:20.622] <1><> ===================================
[2023-10-08 12:01:20.638] <1><> MaaAssistantArknights GUI started
[2023-10-08 12:01:20.638] <1><> Version v4.24.1-alpha.1.d226.g9dd131517
[2023-10-08 12:01:20.653] <1><> Maa ENV: Production
[2023-10-08 12:01:20.653] <1><> User Dir D:\Downloads\MAA_Y
[2023-10-08 12:01:20.653] <1><> ===================================
[2023-10-08 12:01:22.415] <1><> Loading item list from D:\Downloads\MAA_Y\resource\global\YoStarEN\resource\item_index.json
[2023-10-08 12:01:22.546] <7><> Load Resource
[2023-10-08 12:01:22.546] <7><> Load resource: D:\Downloads\MAA_Y\resource
[2023-10-08 12:01:22.546] <7><> AsstLoadResource dirname: D:\Downloads\MAA_Y
[2023-10-08 12:01:22.747] <7><> AsstLoadResource ret: True
[2023-10-08 12:01:22.747] <7><> Load resource: D:\Downloads\MAA_Y\resource\global\YoStarEN\resource
[2023-10-08 12:01:22.747] <7><> AsstLoadResource dirname: D:\Downloads\MAA_Y\resource\global\YoStarEN
[2023-10-08 12:01:22.762] <7><> AsstLoadResource ret: True
[2023-10-08 12:01:22.762] <7><> Load resource: D:\Downloads\MAA_Y\cache\resource
[2023-10-08 12:01:22.762] <7><> AsstLoadResource dirname: D:\Downloads\MAA_Y\cache
[2023-10-08 12:01:22.778] <7><> AsstLoadResource ret: True
[2023-10-08 12:01:22.778] <7><> Load resource: D:\Downloads\MAA_Y\cache\resource\global\YoStarEN\resource
[2023-10-08 12:01:22.778] <7><> AsstLoadResource dirname: D:\Downloads\MAA_Y\cache\resource\global\YoStarEN
[2023-10-08 12:01:22.800] <7><> AsstLoadResource ret: True
[2023-10-08 12:01:23.498] <1><> Whether the window placement was set successfully: true
[2023-10-08 12:01:23.651] <10><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/lastUpdateTime.json
[2023-10-08 12:01:23.952] <10><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/gui/StageActivity.json
[2023-10-08 12:01:24.237] <9><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/resource/tasks.json
[2023-10-08 12:01:24.506] <10><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/resource/global/YoStarEN/resource/tasks.json
[2023-10-08 12:01:24.506] <10><> Load Resource
[2023-10-08 12:01:24.506] <10><> Load resource: D:\Downloads\MAA_Y\resource
[2023-10-08 12:01:24.506] <10><> AsstLoadResource dirname: D:\Downloads\MAA_Y
[2023-10-08 12:01:24.606] <10><> AsstLoadResource ret: True
[2023-10-08 12:01:24.606] <10><> Load resource: D:\Downloads\MAA_Y\resource\global\YoStarEN\resource
[2023-10-08 12:01:24.606] <10><> AsstLoadResource dirname: D:\Downloads\MAA_Y\resource\global\YoStarEN
[2023-10-08 12:01:24.622] <10><> AsstLoadResource ret: True
[2023-10-08 12:01:24.622] <10><> Load resource: D:\Downloads\MAA_Y\cache\resource
[2023-10-08 12:01:24.622] <10><> AsstLoadResource dirname: D:\Downloads\MAA_Y\cache
[2023-10-08 12:01:24.637] <10><> AsstLoadResource ret: True
[2023-10-08 12:01:24.637] <10><> Load resource: D:\Downloads\MAA_Y\cache\resource\global\YoStarEN\resource
[2023-10-08 12:01:24.637] <10><> AsstLoadResource dirname: D:\Downloads\MAA_Y\cache\resource\global\YoStarEN
[2023-10-08 12:01:24.653] <10><> AsstLoadResource ret: True
[2023-10-08 12:01:25.023] <1><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/version/summary.json
[2023-10-08 12:01:25.909] <10><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/version/beta.json
[2023-10-08 12:01:26.257] <1><> HTTP: NotModified GET https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/overview.json
[2023-10-08 12:01:26.542] <1><> HTTP: NotModified GET https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/battle_data.json
[2023-10-08 12:01:41.544] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/infrast.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:01:42.413] <1><> HTTP: NotModified GET https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/item_index.json
[2023-10-08 12:01:57.430] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:01:58.293] <1><> HTTP: NotModified GET https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/stages.json
[2023-10-08 12:02:13.309] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:02:28.313] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:02:43.325] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:02:58.340] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:03:13.348] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:03:28.357] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:03:43.373] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:03:58.388] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:04:13.402] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:04:28.418] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:04:43.439] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarKR/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:04:58.445] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarKR/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:05:13.449] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarKR/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-10-08 12:05:28.464] <1><> Failed to send GET request to "https://ota.maa.plus/MaaAssistantArknights/MaaAssistantArknights/resource/dynamic_list.txt"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()

```
</p>
</details>

**Comment by MistEO** [comment]
The network is congested, we are considering adding a mirror server. :(

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/18511905/0594849f-7cb4-4574-b65f-18811c0324b3)

**Comment by Constrat** [comment]
Oooooh now I understand. Well I'm guessing it's something we should be proud of right?
