### ISSUE TITLE
从传输流收到意外的 EOF 或 0 个字节

### ISSUE THREAD

**Issue by Ubnice** [MaaAssistantArknights/MaaAssistantArknights#6769]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

commit 8e8cfe0 修复后新版本再次发生“从传输流收到意外的 EOF 或 0 个字节"，但MAA没有崩溃，继续执行任务。触发时间为基建制造站换班

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840746/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/12840747/gui.log)

### 还有别的吗？

```
错误信息：
MAA 遇到了问题
Received an unexpected EOF or 0 bytes from the transport stream.
解决方案
出现未知错误
详细信息
System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Models.ResourceUpdater.<UpdateFileWithETag>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MaaWpfGui.Models.ResourceUpdater.<UpdateSingleFiles>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Models.ResourceUpdater.<Update>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<CheckAndDownloadUpdate>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<ShowUpdateOrDownload>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Constrat** [comment]
@zzyyyl

**Comment by Constrat** [comment]
You are not running the latest version. You are on 4.24.0

**Comment by Constrat** [comment]
Duplicate of https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6561
