### ISSUE TITLE
OTA Game updates takes a long time

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#7261]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.

### Description

Game resources are being updated takes a huge amount of time.
Is this related to too much traffic?

### Log files

<details><summary>Details</summary>
<p>

```py
[2023-11-10 12:50:57.018] <14><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/lastUpdateTime.json
[2023-11-10 12:50:57.219] <1><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/version/summary.json
[2023-11-10 12:50:57.673] <1><> HTTP: OK GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/version.json
[2023-11-10 12:50:58.240] <1><> HTTP: NotModified GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/dynamic_list.txt
[2023-11-10 12:50:59.631] <1><> HTTP: NotModified GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/overview.json
[2023-11-10 12:51:00.915] <1><> HTTP: NotModified GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/stages.json
[2023-11-10 12:51:16.937] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:51:32.971] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:51:48.989] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/battle_data.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:51:50.268] <1><> HTTP: NotModified GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/infrast.json
[2023-11-10 12:51:51.563] <1><> HTTP: NotModified GET https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/recruitment.json
[2023-11-10 12:52:07.568] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:52:23.587] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:52:39.618] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:52:55.643] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:53:11.663] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:53:27.667] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:53:43.702] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:53:59.727] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-10 12:54:15.745] <1><> Failed to send GET request to "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarKR/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()

```

</p>
</details>

**Comment by ABA2396** [comment]
The GET request didn't go through. I think it's a network problem.

**Comment by Constrat** [comment]
With my network?

**Comment by ABA2396** [comment]
r2 By definition it should be distributed globally, try rechecking for updates in settings? The alpha is now showing progress

**Comment by ABA2396** [comment]
Re-posted a nightly, the previous one would show up at 100% after the update (which was actually done)

**Comment by Constrat** [comment]
I've updated and it doesn't seem like anything 's changed

**Comment by Constrat** [comment]
```
[2023-11-11 15:40:24.124] <13><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/lastUpdateTime.json
[2023-11-11 15:40:24.889] <1><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/version/summary.json
[2023-11-11 15:40:26.017] <1><> HTTP: OK GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/version.json
[2023-11-11 15:40:26.635] <1><> HTTP: NotModified GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/dynamic_list.txt
[2023-11-11 15:40:28.843] <1><> HTTP: NotModified GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/overview.json
[2023-11-11 15:40:31.728] <1><> HTTP: NotModified GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/stages.json
[2023-11-11 15:40:47.730] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:41:03.751] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:41:19.762] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/battle_data.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:41:35.774] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/infrast.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:41:51.776] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:42:07.792] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:42:23.805] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarJP/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:42:39.808] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:42:55.807] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:42:57.966] <1><> HTTP: NotModified GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/YoStarEN/resource/version.json
[2023-11-11 15:43:00.010] <1><> HTTP: NotModified GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/recruitment.json
[2023-11-11 15:43:16.024] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/item_index.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-11 15:43:32.040] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/global/txwy/resource/version.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()

```

**Comment by ABA2396** [comment]
Maybe it's the server. I don't know. Somebody else has to look at it
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6b8a4627-67b6-4ce4-a715-bd2f0440cb51)

**Comment by ABA2396** [comment]
a0475da1e37c812b55ed9d7281d77e0a4bed9584 fixed

**Comment by Constrat** [comment]
![Uploading image.png…]()

**Comment by Constrat** [comment]
@ABA2396 do you have a list of the various Mirrors? because maybe https://s3.maa-org.net:25240 doesn't work properly but gets selected nonetheless. In different machines and on different networks I always get the same issue of game data not updating.

**Comment by Constrat** [comment]
```js
[2023-11-15 17:46:00.924] <13><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/lastUpdateTime.json
[2023-11-15 17:46:01.568] <1><> HTTP: OK GET https://ota.maa.plus/MaaAssistantArknights/api/version/summary.json
[2023-11-15 17:46:02.538] <1><> Failed to send GET request to "https://maa-ota.annangela.cn/MaaAssistantArknights/MaaAssistantArknights/resource/version.json"
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'maa-ota.annangela.cn'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
[2023-11-15 17:46:04.188] <1><> HTTP: OK GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/version.json
[2023-11-15 17:46:05.058] <1><> HTTP: OK GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/version.json
[2023-11-15 17:46:06.257] <1><> HTTP: OK GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/dynamic_list.txt
[2023-11-15 17:46:09.393] <1><> HTTP: OK GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/Arknights-Tile-Pos/overview.json
[2023-11-15 17:46:21.998] <1><> HTTP: NotModified GET https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/stages.json
[2023-11-15 17:46:38.017] <1><> Failed to send GET request to "https://s3.maa-org.net:25240/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource/recruitment.json"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaaWpfGui.Services.Web.HttpService.<GetAsync>d__9.MoveNext()
```
maa-ota.annangela.cn directly is not recognized (probably because of overseas location, but s3.maa-org.net seems to work sometimes and sometimes not. I can't understand what is the issue.
cc @MistEO @AnnAngela

**Comment by AnnAngela** [comment]
The mirrors list:

- `https://s3.maa-org.net:25240/maa-resources/` - locate in CN Mainland, s3 compatiable
- `https://maa-ota.annangela.cn/` - Block overseas access via fake DNS resolution to avoid excessive fees
- `https://ota.maa.plus/` - Aliyun HK
- `https://maa.r2.imgg.dev/` - Cloudflare R2

@MistEO told me that when one mirror is inaccessible, another mirror will be automatically tried.

Maybe you should check system proxy configuration(Use the Run dialog to exec `ms-settings:network-proxy`) or MAA built-in one:

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/9762652/2ac4e424-3b85-402e-8e12-2373d3d9a053)

**Comment by ABA2396** [comment]
> MistEO told me that when one mirror is inaccessible, another mirror will be automatically tried.

It's really only the first time that you'll try to determine which one will connect, but after you've determined the mirror, it's the same one you access every time (to make sure that the fetched etag isn't a problem?).

```
private static async Task<string> GetResourceApi()
{
    string mirror = ConfigurationHelper.GetValue(ConfigurationKeys.ResourceApi, string.Empty);
    if (!string.IsNullOrEmpty(mirror))
    {
        return mirror;
    }

    var mirrorList = new List<string>
    {
        MaaUrls.S3ResourceApi,
        MaaUrls.R2ResourceApi,
        MaaUrls.AnnMirrorResourceApi,
    };

    while (mirrorList.Count != 0)
    {
        // random select a mirror
        var index = new Random().Next(0, mirrorList.Count);
        var mirrorUrl = mirrorList[index];

        var response = await Instances.HttpService.GetAsync(new Uri(mirrorUrl + MaaResourceVersion), httpCompletionOption: HttpCompletionOption.ResponseHeadersRead);
        if (response is { StatusCode: System.Net.HttpStatusCode.OK })
        {
            mirror = mirrorUrl;
            break;
        }

        mirrorList.RemoveAt(index);
    }

    if (string.IsNullOrEmpty(mirror))
    {
        mirror = MaaUrls.MaaResourceApi;
    }

    ConfigurationHelper.SetValue(ConfigurationKeys.ResourceApi, mirror);
    return mirror;
}
```

**Comment by AnnAngela** [comment]
> to make sure that the fetched etag isn't a problem?
In fact the mirrors can be grouped like this:

1. `https://s3.maa-org.net:25240/maa-resources/` & `https://maa.r2.imgg.dev/`: these are both S3-compatiable, so these will produce the same etag
2. `https://ota.maa.plus/` & `https://maa-ota.annangela.cn/`: the latter acts as a proxy for the former through CDN, so these will produce the same etag too

And both group has 1 mainland mirror and 1 oversea one, so I think the client can choose one of the group and try the both mirrors of the group.

**Comment by MistEO** [comment]
But... why do network errors occur? Maybe we should add some servers in Europe or somewhere else?

**Comment by Constrat** [comment]
I couldn't get to the bottom of it.

**Comment by ABA2396** [comment]
> I couldn't get to the bottom of it. I can open the links manually in the browser, instead of directly throwing an exception, how about trying again?

I'll add the retry mechanism tomorrow, though it doesn't always feel like it's going to work.

**Comment by Constrat** [comment]
Won't hurt trying. Even though it's strange.

**Comment by Constrat** [comment]
Passing discussion to:
Link to
- #7329
