### ISSUE TITLE
Linux 环境下目录路径识别可能有错

### ISSUE THREAD

**Issue by SummerDiver** [MaaAssistantArknights/MaaAssistantArknights#7420]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况

### 问题描述

> 搜了以下，大概跟这个 issue 是一样的：[linux使用maa错误](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5529)

环境为Ubuntu 20.04，执行 python3 sample.py 时会报错：
```
Process Process-1:
Traceback (most recent call last):
  File "/home/xiayuang/MAA-v4.27.0-linux-x86_64/Python/asst/asst.py", line 65, in load
    Asst.__lib = lib_import_func(str(Asst.__libpath))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: libMaaCore.so: cannot open shared object file: No such file or directory**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xiayuang/MAA-v4.27.0-linux-x86_64/Python/asst/updater.py", line 35, in _get_cur_version
    Asst.load(path=path)
  File "/home/xiayuang/MAA-v4.27.0-linux-x86_64/Python/asst/asst.py", line 68, in load
    Asst.__lib = lib_import_func(str(Asst.__libpath))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: None: cannot open shared object file: No such file or directory
^CTraceback (most recent call last):
  File "sample.py", line 26, in <module>
    Updater(path, Version.Stable).update()
  File "/home/xiayuang/MAA-v4.27.0-linux-x86_64/Python/asst/updater.py", line 51, in __init__
    self.cur_version = q.get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 97, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
```

我自己尝试查看了一下，感觉可能是 sample.py 第 23 行获取文件路径有误，获取成了相对变量，以下代码输出为 `.` ：

```python
    path = pathlib.Path(__file__).parent.parent
    print(path)
```

尝试了一下，可能改为 `path = pathlib.Path(__file__).resolve().parent.parent` 可以解决问题。

### 日志文件

无

### 截图

无

**Comment by zzyyyl** [comment]
来个 PR：）
