### ISSUE TITLE
MAA 关闭软件后无法重新启动

### ISSUE THREAD

**Issue by dlawang** [MaaAssistantArknights/MaaAssistantArknights#7794]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

关闭MAA软件之后重新启动灰报错，必须重启电脑，等待开机自行启动
错误： The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
详细信息：  at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor(IContainer container)
   at lambda_method(Closure , IRegistrationContext )
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Main.AsstProxy..ctor(IContainer container, IWindowManager windowManager)
   at lambda_method(Closure , IRegistrationContext )
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.ViewModels.UI.RootViewModel..ctor(IContainer container)
   at lambda_method(Closure , IRegistrationContext )
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at Stylet.Bootstrapper`1.get_RootViewModel()
   at Stylet.Bootstrapper`1.Launch()
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13776085/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13776086/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57072962/6e3534c5-9dd1-4e90-b363-29f9ffbec7b4)

**Comment by ABA2396** [comment]
你这用的啥古早版本，已经是八个月前的东西了

**Comment by dlawang** [comment]
> 你这用的啥古早版本，已经是八个月前的东西了

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/57072962/34a59214-f061-4406-9b57-c40ca6e3e483)
这是我现在的版本号

**Comment by status102** [comment]
> ![image](https://private-user-images.githubusercontent.com/57072962/293091191-34a59214-f061-4406-9b57-c40ca6e3e483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MjQwMDYsIm5iZiI6MTcwMzcyMzcwNiwicGF0aCI6Ii81NzA3Mjk2Mi8yOTMwOTExOTEtMzRhNTkyMTQtZjA2MS00NDA2LTliNTctYzQwY2E2ZTNlNDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDAwMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YTRkZjhiZDQ0ZTZmYWUyY2RkODE3MDMzOTlhMjBlZDgzMzNmZTJhMzlhMmUyMjJmNTJlN2VkMjkxOTRlN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UWvEnQC6VHw31-6bgZQg3YoCXhaBSy_mu0ytcjfqB_c) 这是我现在的版本号

asst.log内为4月的内容
