### ISSUE TITLE
MAA Fatal Unknown Error Error gb2313 is not a supported encoding name

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaAssistantArknights#7874]
This occurred during the OperBox detection task

MAA has encountered an error
'gb2312' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
Solution
Unknown error occurred
Details
```
System.ArgumentException: 'gb2312' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at MaaWpfGui.ViewModels.UI.RecognizerViewModel.PadRightEx(String str, Int32 totalByteCount)
   at MaaWpfGui.ViewModels.UI.RecognizerViewModel.OperBoxParse(JObject details)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskExtraInfo(JObject details)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskMsg(AsstMsg msg, JObject details)
   at MaaWpfGui.Main.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   at MaaWpfGui.Main.AsstProxy.<>c__DisplayClass17_0.<CallbackFunction>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
@ABA2396 .NET8?

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/56174894/ff12125b-5bfa-4c32-a5d5-d73a0cf4b08d)

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/dbef8075beadbd836116d33c89735b637797a84a fixed
