### ISSUE TITLE
不能打开maa

### ISSUE THREAD

**Issue by skiasuna** [MaaAssistantArknights/MaaAssistantArknights#7881]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
The process cannot access the file 'D:\神的游戏\maa\resource\dynamic_list.txt.tmp' because it is being used by another process.
解决方案
出现未知错误
详细信息
System.IO.IOException: The process cannot access the file 'D:\神的游戏\maa\resource\dynamic_list.txt.tmp' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MaaWpfGui.Helper.HttpResponseHelper.SaveResponseToFileAsync(HttpResponseMessage response, String saveTo, Boolean saveAndDeleteTmp)
   at MaaWpfGui.Models.ResourceUpdater.UpdateFileWithETag(String baseUrl, String file, String saveTo, Int32 maxRetryTime)
   at MaaWpfGui.Models.ResourceUpdater.UpdateFilesWithIndex(String baseUrl, Int32 maxRetryTime)
   at MaaWpfGui.Models.ResourceUpdater.Update()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndDownloadUpdate()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.ShowUpdateOrDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

MAA 遇到了问题
The process cannot access the file 'D:\神的游戏\maa\resource\dynamic_list.txt.tmp' because it is being used by another process.
解决方案
出现未知错误
详细信息
System.IO.IOException: The process cannot access the file 'D:\神的游戏\maa\resource\dynamic_list.txt.tmp' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MaaWpfGui.Helper.HttpResponseHelper.SaveResponseToFileAsync(HttpResponseMessage response, String saveTo, Boolean saveAndDeleteTmp)
   at MaaWpfGui.Models.ResourceUpdater.UpdateFileWithETag(String baseUrl, String file, String saveTo, Int32 maxRetryTime)
   at MaaWpfGui.Models.ResourceUpdater.UpdateFilesWithIndex(String baseUrl, Int32 maxRetryTime)
   at MaaWpfGui.Models.ResourceUpdater.Update()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndDownloadUpdate()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.ShowUpdateOrDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
文件被占用了，这玩意重启就好了吧？
