### ISSUE TITLE
maa 4.28.8内测版 小工具干员识别出错

### ISSUE THREAD

**Issue by emiyax** [MaaAssistantArknights/MaaAssistantArknights#7885]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

Maa识别
MAA 小工具干员识别出错，会一直跳出错误弹窗。怀疑是识别过程中，中文编码出错。
下面是错误信息：
'gb2312' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
解决方案
出现未知错误
详细信息
System.ArgumentException: 'gb2312' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at MaaWpfGui.ViewModels.UI.RecognizerViewModel.PadRightEx(String str, Int32 totalByteCount)
   at MaaWpfGui.ViewModels.UI.RecognizerViewModel.OperBoxParse(JObject details)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskExtraInfo(JObject details)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskMsg(AsstMsg msg, JObject details)
   at MaaWpfGui.Main.AsstProxy.ProcMsg(AsstMsg msg, JObject details)
   at MaaWpfGui.Main.AsstProxy.<>c__DisplayClass17_0.<CallbackFunction>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13819187/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13819188/gui.log)
在2024/1/3 21:03附近

### 截图

![批注 2024-01-03 210640](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/105486851/ce52fecc-3261-4875-b116-41cafe5b0d8a)

### 还有别的吗？

使用mumu12模拟器。
安装.net 8后出现的问题。
怀疑是.net 8中gb2312资源问题。不能正确的转换成中文。

**Comment by Manicsteiner** [comment]
已修复 https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/dbef8075beadbd836116d33c89735b637797a84a 请等待更新

**Comment by Constrat** [comment]
> - [x] I've checked the pinned issue to make sure my issue isn't being mentioned.


- #7732
  - https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/7874
fixed in yet to be released
