### ISSUE TITLE
启动时提示，请求的操作需要提升，从而导致无法正常打开MAA，于本周出现

### ISSUE THREAD

**Issue by jordanmaxis** [MaaAssistantArknights/MaaAssistantArknights#7890]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

<img width="450" alt="Snipaste_2024-01-03_23-16-29" src="https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/46923757/decfe681-e8cf-4a5d-84a6-7aadf71c8622">
如上图所示，如果图片未正常显示请踢我一脚

### 日志文件

MAA 遇到了问题
An error occurred trying to start process 'E:\mumu\emulator\nemu\EmulatorShell\NemuPlayer.exe' with working directory 'D:\tools\MAA-v4.19.3-win-x64'. 请求的操作需要提升。
解决方案
出现未知错误
详细信息
System.ComponentModel.Win32Exception (740): An error occurred trying to start process 'E:\mumu\emulator\nemu\EmulatorShell\NemuPlayer.exe' with working directory 'D:\tools\MAA-v4.19.3-win-x64'. 请求的操作需要提升。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.TryToStartEmulator(Boolean manual)
   at MaaWpfGui.Main.AsstProxy.<>c.<Init>b__14_2()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.Main.AsstProxy.<Init>b__14_1()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
试试管理员权限启动

**Comment by jordanmaxis** [comment]
管理员权限启动可以了，但是不能理解的是之前并没有类似问题，难道以后每一次都需要使用管理员权限启动？

**Comment by ABA2396** [comment]
#7908 fixed

**Comment by ABA2396** [comment]
> 管理员权限启动可以了，但是不能理解的是之前并没有类似问题，难道以后每一次都需要使用管理员权限启动？

右键-属性-兼容性-以管理员身份运行此程序
或许和mumu的更新也有关系？一般来说非管理员权限启动的软件都是打不开管理员权限的软件的
