### ISSUE TITLE
突然报错了

### ISSUE THREAD

**Issue by zeto1979** [MaaAssistantArknights/MaaAssistantArknights#8005]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
The process cannot access the file 'C:\脚本\MAA_win7.exe' because it is being used by another process.
解决方案
出现未知错误
详细信息
System.IO.IOException: The process cannot access the file 'C:\脚本\MAA_win7.exe' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   at MaaWpfGui.ViewModels.UI.RootViewModel.CheckAndUpdateNow()
   at MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   at Stylet.Screen.<Stylet.IViewAware.AttachView>b__42_0(Object o, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13928192/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/13928193/gui.log)

**Comment by zeto1979** [comment]
![20240113215855](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/144797799/7596ca8e-2763-4c87-9b7c-84827f0132c8)
重启也是这个

**Comment by ABA2396** [comment]
所以为啥还在用着MAA_win7
