### ISSUE TITLE
MAA闪退关于MaaCore.dll

### ISSUE THREAD

**Issue by zuoshiyue** [MaaAssistantArknights/MaaAssistantArknights#8041]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

N100芯片主机安装EXSI并安装window11系统，运行MAA发生闪退现象，以下是复制的详细内容Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)

### 日志文件

MAA 遇到了问题
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
解决方案
请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method17(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/65be6167-c585-4bf1-96c1-afad8b41f648)
跟着这个走过了吗

**Comment by zuoshiyue** [comment]
我的问题已经得到了解决，虽然不清楚具体的原因是什么。我加入了我们的QQ群，参照公告进行了一些处理。
我没有关注到具体问题是什么，比较大的猜测是我的系统新装完之后，相关的一些依赖是不够健全的，导致的启动失败。不过我们的报错信息可能提示的不够完善，对于普通用户而言可能相对不是很友好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月19日(星期五) 中午11:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MaaAssistantArknights/MaaAssistantArknights] MAA闪退关于MaaCore.dll (Issue #8041)





 
image.png (view on web)
 跟着这个走过了吗

**Comment by ABA2396** [comment]
常见问题-闪退里很清楚的说了，那这个就是缺vc++的运行库，常见问题的链接都给你红字高亮显示了，自己不看说描述不清楚？
