### ISSUE TITLE
v5.0.0-beta.2.d027 至 v5.0.0-beta.2.d032 版本自动更新功能出错，需要手动解压升级包

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#8129]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

可正常下载增量包 重启解压报错
删除下载的增量包后可正常启动 并再次下载增量包
重启后再次解压报错

### Version

v5.0.0-beta.2.d027.gb56eaa948
更新至
v5.0.0-beta.2.d032.g1bc32ff06

### 日志文件

```
MAA 遇到了问题
Object reference not set to an instance of an object.
解决方案
出现未知错误
详细信息
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaaWpfGui.Helper.ToastNotification.Show()
   at MaaWpfGui.Helper.ToastNotification.Show(Double lifeTime, UInt32 row, NotificationSounds sound, NotificationContent notificationContent)
   at MaaWpfGui.Helper.ToastNotification.ShowMore(Double lifeTime, UInt32 row, NotificationSounds sound, NotificationContent notificationContent)
   at MaaWpfGui.Helper.ToastNotification.ShowUpdateVersion(UInt32 row)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<CheckAndUpdateNow>b__33_0()
   at Stylet.Execute.OnUIThreadAsync(Action action)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   at MaaWpfGui.Main.Bootstrapper.DisplayRootView(Object rootViewModel)
   at Stylet.Bootstrapper`1.Launch()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Rbqwow** [comment]
点击`复制错误信息`会出现另一个错误弹窗，但实际上已成功复制。
```
MAA 遇到了问题
OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()
   at MaaWpfGui.Views.UI.ErrorView.CopyErrorMessage_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by zzyyyl** [comment]
d027死档辣！d032本身没问题（大概

**Comment by zzyyyl** [comment]
可以先将文件夹内压缩包删除，然后等待d033

**Comment by ABA2396** [comment]
得等那个包打完看看行不行

**Comment by Rbqwow** [comment]
> 可以先将文件夹内压缩包删除（删了压缩包之后应该能正常打开 MAA），然后等待 d033

喜报 033也似了 报错一模一样

**Comment by ABA2396** [comment]
> 可以先将文件夹内压缩包删除（删了压缩包之后应该能正常打开 MAA），然后等待 d033

这个方法没用，只能d24之前的更新到d033,d027和d032更新到别的版本都会有问题

**Comment by ABA2396** [comment]
这次的都是增量更新，手动解压更新包覆盖安装应该就可以了

**Comment by vic233333** [comment]
![98e747484bb675dd9e23f120959e3ff6](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/93087330/4bf0a526-ed57-46a1-8b52-8bd9f2041e90)
就这个打开，然后把里面东西拖出来全部覆盖就行。

**Comment by ABA2396** [comment]
[d033](https://github.com/MaaAssistantArknights/MaaRelease/releases) 及之后版本 fixed，d027及d032版本需要手动解压

**Comment by zzyyyl** [comment]
简便一点，只需要把包里的 MAA.exe 先解压出来，再打开这个 MAA.exe 让它自己解压其它文件就完事了

**Comment by huwei9811** [comment]
解压之后保留压缩包不要删除，不然会一直死循环

**Comment by 957176113** [comment]
手动解压覆盖也启动失败

**Comment by vic233333** [comment]
> 手动解压覆盖也启动失败

重新下个完整包安装试一下

**Comment by 624565299** [comment]
这个问题还是存在啊？公告说是解压那个压缩包，解压替换完了是能打开正常运行了但是下一次重启开机还是会弹出这个Object reference not set to an instance of an object.

**Comment by ABA2396** [comment]
> 这个问题还是存在啊？公告说是解压那个压缩包，解压替换完了是能打开正常运行了但是下一次重启开机还是会弹出这个Object reference not set to an instance of an object.

解压替换完之后别删压缩包，要让maa再自己解压一次
