### ISSUE TITLE
maa启动报错

### ISSUE THREAD

**Issue by aioi50** [MaaAssistantArknights/MaaAssistantArknights#8136]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

maa无法启动，弹出报错窗口
MAA 遇到了问题
Object reference not set to an instance of an object.

### Version

[v5.0.0-beta.2.d034.gd520dad86]

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14132269/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14132271/gui.log)
报错信息：System.NullReferenceException: Object reference not set to an instance of an object.
   at MaaWpfGui.Helper.ToastNotification.Show()
   at MaaWpfGui.Helper.ToastNotification.Show(Double lifeTime, UInt32 row, NotificationSounds sound, NotificationContent notificationContent)
   at MaaWpfGui.Helper.ToastNotification.ShowMore(Double lifeTime, UInt32 row, NotificationSounds sound, NotificationContent notificationContent)
   at MaaWpfGui.Helper.ToastNotification.ShowUpdateVersion(UInt32 row)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.<CheckAndUpdateNow>b__33_0()
   at Stylet.Execute.OnUIThreadAsync(Action action)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   at MaaWpfGui.Main.Bootstrapper.DisplayRootView(Object rootViewModel)
   at Stylet.Bootstrapper`1.Launch()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aioi50** [comment]
完整包覆盖后解决了
