### ISSUE TITLE
MAA 遇到了问题 OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN)) 解决方案 出现未知错误 详细信息 System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)    at System.Windows.Clipboard.Flush()    at MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()    at MaaWpfGui.Views.UI.ErrorView.CopyErrorMessage_Click(Object sender, RoutedEventArgs e)    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### ISSUE THREAD

**Issue by YUSHEN0814** [MaaAssistantArknights/MaaAssistantArknights#8144]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()
   at MaaWpfGui.Views.UI.ErrorView.CopyErrorMessage_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

MAA 遇到了问题
OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()
   at MaaWpfGui.Views.UI.ErrorView.CopyErrorMessage_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 日志文件

MAA 遇到了问题
OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()
   at MaaWpfGui.Views.UI.ErrorView.CopyErrorMessage_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 截图

MAA 遇到了问题
OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()
   at MaaWpfGui.Views.UI.ErrorView.CopyErrorMessage_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 还有别的吗？

MAA 遇到了问题
OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard 失败 (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at MaaWpfGui.Views.UI.ErrorView.CopyToClipboard()
   at MaaWpfGui.Views.UI.ErrorView.CopyErrorMessage_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Cryolitia** [comment]
你是不是点了复制剪贴板，复制不了，不是什么大问题，也没得修

**Comment by ABA2396** [comment]
> 你是不是点了复制剪贴板，复制不了，不是什么大问题，也没得修

直接catch然后ignore了
