### ISSUE TITLE
更新完就出问题了

### ISSUE THREAD

**Issue by kkusala123** [MaaAssistantArknights/MaaAssistantArknights#8287]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
该类型的 CollectionView 不支持从调度程序线程以外的线程对其 SourceCollection 进行的更改。
解决方案
出现未知错误
详细信息
System.NotSupportedException: 该类型的 CollectionView 不支持从调度程序线程以外的线程对其 SourceCollection 进行的更改。
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.AddLog(String content, String color, String weight)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass80_0.<ConnectToEmulator>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Core Version: v5.1.0-beta.2
UI Version: v5.1.0-beta.2

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14205129/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14205130/asst.log)

**Comment by ABA2396** [comment]
@Rbqwow 这玩意会不会和删了mumu6有关

**Comment by Rbqwow** [comment]
> @Rbqwow 这玩意会不会和删了mumu6有关

在测了

**Comment by status102** [comment]
```
[2024-02-08 14:35:47.629][INF][Px4e4c][Tx2100] Assistant::append_callback | ConnectionInfo {"details":{"adb":"adb/platform-tools/adb.exe","address":"127.0.0.1:7555","config":"MuMuEmulator"},"uuid":"","what":"ConnectFailed","why":"ConfigNotFound"}
```

**Comment by ABA2396** [comment]
干脆把public void AddLog套一层ui线程吧

**Comment by KevinT3Hu** [comment]
可以稳定复现吗

**Comment by ABA2396** [comment]
> 并不是。而是他没有开管理员启动。MAA连接mumu6需要管理员启动。

这是两个问题，检测失败会打一个日志，但在非ui线程打日志会报线程错误
