### ISSUE TITLE
加载EXE闪退，报错“找不到指定的模块'MaaCore.dll'”

### ISSUE THREAD

**Issue by Ricardo-pluto** [MaaAssistantArknights/MaaAssistantArknights#8367]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

启动MAA报错，以管理员身份启动依然报错，信息为找不到指定的模块'MaaCore.dll' ，
可以确定的是MAA.exe与该dll在同一文件夹位置，解压后没有移动过
系统是win10专业版，首次启动时系统给出无法识别的应用被阻止提示，图片见下方，
猜测为win10防火墙问题，关闭防火墙后重新启动，问题复现。
.net 8.0已经安装，详细信息给到日志文件部分。

### Version

5.0，5.1版本均有尝试。

### 日志文件

MAA 遇到了问题
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
解决方案
请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel..ctor()
   at lambda_method27(Closure, IRegistrationContext)
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34275852/eef1280a-46fa-4add-917e-f9a33e2cb248)
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34275852/2080907e-4f62-4e0c-8b77-14270092d85f)

**Comment by Constrat** [comment]
Again with the Windows Defender shit

**Comment by ABA2396** [comment]
请参考文档: 常见问题 - 闪退 进行操作。

**Comment by ABA2396** [comment]
> Unable to load DLL

`Unable to load DLL` is more likely to be a missing runtime library.

**Comment by Ricardo-pluto** [comment]
找到问题了，少下载了这个组件库：“Visual C++ Redistributable”
关于.net8的提示非常明显，结果我忽略了另一个组件库，
给各位添麻烦了，不好意思。
稍后我将关闭这个issues
