### ISSUE TITLE
MAATouch 在 Android 14 上点击无效（MaaTouch 发生崩溃）

### ISSUE THREAD

**Issue by cubesky** [MaaAssistantArknights/MaaAssistantArknights#8430]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在 Android 14 上使用 MAA 界面和 MAA Cli 会发生触控无效的问题。

测试后发现是 MAATouch 在 Android 14 上接收到 InputManager 所需的操作时发生崩溃

```
OnePlus7Pro:/ $ app_process /data/local/tmp com.shxyke.MaaTouch.App
^ 10 1440 3120 255
$ 255
d 0 10 10 50
c
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.shxyke.MaaTouch.wrappers.ServiceManager.getInputManager(ServiceManager.java:50)
        at com.shxyke.MaaTouch.Controller.injectEvent(Controller.java:45)
        at com.shxyke.MaaTouch.Controller.injectTouch(Controller.java:125)
        at com.shxyke.MaaTouch.Controller.injectTouchDown(Controller.java:72)
        at com.shxyke.MaaTouch.ControlThread.handleMessage(ControlThread.java:24)
        at com.shxyke.MaaTouch.ControlThread.run(ControlThread.java:66)
        at com.shxyke.MaaTouch.App.main(App.java:33)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:207)
        at android.hardware.input.InputManager.getInstance(InputManager.java:271)
        ... 10 more
Killed
137|OnePlus7Pro:/ $
```

### Version

Resource Version: 千秋一粟

UI Version: v5.1.1-alpha.1.d118.g999f9087b

Core Version: v5.1.1-alpha.1.d118.g999f9087b

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14438937/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/14438939/asst.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/8038511/f247a1c1-d370-419f-833b-cf391490a9e7)

### 还有别的吗？

Android 版本: Android 14 (LineageOS 21)

手机: OnePlus 7 Pro

已 PR 了一个修复 https://github.com/MaaAssistantArknights/MaaTouch/pull/4

**Comment by Cryolitia** [comment]
https://github.com/MaaAssistantArknights/MaaTouch/pull/4
