### ISSUE TITLE
常见问题-闪退：不存在该问题的有效解决办法

### ISSUE THREAD

**Issue by PlayerRan** [MaaAssistantArknights/MaaAssistantArknights#8567]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

1.双击MAA后闪退，弹出错误窗栏
2.使用管理员运行后，情况完全没有改变

### Version

Resourse Version:5.10

### 日志文件

MAA 遇到了问题
The type initializer for 'MaaWpfGui.Helper.DataHelper' threw an exception.
Unexpected character encountered while parsing value: �. Path '', line 0, position 0.
解决方案
请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.Helper.DataHelper' threw an exception.
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: �. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at MaaWpfGui.Helper.DataHelper..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.Helper.DataHelper.GetLocalizedCharacterName(String characterName, String language)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.UpdateRoguelikeCoreCharList()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.InitRoguelike()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.Init()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
没太看懂，感觉像是你 `resource/battle_data.json` 文件出问题了，下载一份https://github.com/MaaAssistantArknights/MaaResource/blob/main/resource/battle_data.json 里的替换下看看

**Comment by ABA2396** [comment]
自己没动过这个文件吗？照理来说MAA这些文件都是不会带BOM头的

**Comment by PlayerRan** [comment]
> 自己没动过这个文件吗？照理来说MAA这些文件都是不会带BOM头的

问题出在硬盘坏道了，重装到固态上就没事了（捂脸）

**Comment by status102** [comment]
看上去解决了，那先close
