### ISSUE TITLE
macOS maadeps-download.py certificate verify failed error

### ISSUE THREAD

**Issue by RieLCho** [MaaAssistantArknights/MaaAssistantArknights#8798]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Hi I've tried to contribute maaMacGui and by downloading latest binaries with `maadeps-download.py`, my console said I have a SSL certificate error. 

https://github.com/orgs/MaaAssistantArknights/discussions/8771#discussioncomment-9044287

https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
I guess this is macOS issue, but since I've wasted my time running this script, I guess some hints (maybe a error message,  an annotation or maybe exception handling with macOS) would be very helpful to macOS devs. 

If this isn't helpful to maa contribution, please feel free to close this issue.
Thanks. 

### Version

git hash: 56122a6af22b3596d34428eeaac9ed87f11a5ed4
macOS 14.1
python 3.11.2

### Log files

```
➜  MaaAssistantArknights git:(dev) python maadeps-download.py 
about to download prebuilt dependency libraries for arm64-osx of 2023-04-24-3
to specify another triplet [and tag], run `maadeps-download.py <target triplet> [tag]`
e.g. `maadeps-download.py arm64-windows` or `maadeps-download.py arm64-windows 2023-04-24-3`
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yangjin.cho/Desktop/MaaAssistantArknights/maadeps-download.py", line 157, in <module>
    main()
  File "/Users/yangjin.cho/Desktop/MaaAssistantArknights/maadeps-download.py", line 115, in main
    resp = retry_urlopen(req).read()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/yangjin.cho/Desktop/MaaAssistantArknights/maadeps-download.py", line 79, in retry_urlopen
    resp: http.client.HTTPResponse = urllib.request.urlopen(*args, **kwargs)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>
```

### Anthing else?

Btw, i've tried to build my own binaries, but the MaaDeps/build.py doesn't work for me on macOS 14.1
https://github.com/orgs/MaaAssistantArknights/discussions/8771#discussion-6453301

**Comment by RieLCho** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10603
