### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by QINKOBUNN** [MaaAssistantArknights/MaaAssistantArknights#8907]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

MAA に問題が発生しました
The type initializer for 'MaaWpfGui.Helper.DataHelper' threw an exception.
Error reading JObject from JsonReader. Path '', line 1, position 335669.
解決策
ドキュメント「よくある問題 - クラッシュ」を参照してください。
詳細情報
System.TypeInitializationException: The type initializer for 'MaaWpfGui.Helper.DataHelper' threw an exception.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 335669.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at MaaWpfGui.Helper.DataHelper..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.Helper.DataHelper.GetLocalizedCharacterName(String characterName, String language)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.UpdateRoguelikeCoreCharList()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.InitRoguelike()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.Init()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

5.2.1

### Log files

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15130545/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15130547/gui.log)

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/49424048/c19e80f6-5812-4a4c-9eae-63dbfaa27433)

**Comment by moomiji** [comment]
Version v5.2.1，应该是 json 的问题

**Comment by shenidme** [comment]
没安装[VCRedist x64](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by grassfish1122** [comment]
楼上神医，亲测此报错安装`VCRedist x64`后解决

**Comment by Constrat** [comment]
If solved, close issue. Simple.
