### ISSUE TITLE
异常退出且重启MAA无法解决：External component has thrown an exception.

### ISSUE THREAD

**Issue by CaliInn-Li** [MaaAssistantArknights/MaaAssistantArknights#9102]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

只要点击Link Start!就会在一段时间后抛出异常。
异常信息：
MAA 遇到了问题
External component has thrown an exception.
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass79_0.<ConnectToEmulator>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

UI Version: v5.3.0-beta.1.d005.g16036b1b5
Core Version: v5.3.0-beta.1.d005.g16036b1b5

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15292987/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15292989/gui.log)
时间点为20:22

**Comment by CaliInn-Li** [comment]
10分钟后再次启动可正常使用

**Comment by ABA2396** [comment]
有改过mumu的设置吗
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9017

**Comment by CaliInn-Li** [comment]
今天再次出现这个问题，错误信息一模一样：
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/40906144/fe4f1a8b-50e0-4dd5-b9c3-05628729d302)

只需点击Link Start!即可触发，重启maa无效，问题仍然存在

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/8109
那几个issue都是能连上但是获取不了android_id

**Comment by XuanSuHS** [comment]
> 我的问题和#9017不同，我的adb可以立即连接：

我的 adb 也是可以马上连上，问题出现在连上之后一段时间内无法执行任何命令
你可以执行下面这段验证一下
```
adb disconnect 127.0.0.1:16384 && adb connect 127.0.0.1:16384 && adb shell settings get secure android_id
```
如果明显需要等一段时间（我这是 30s）才能执行完毕就说明也是这个问题，可以参考 #9017 下面的一些方法临时绕过一下

**Comment by CaliInn-Li** [comment]
> > 我的问题和#9017不同，我的adb可以立即连接：
> 
> 我的 adb 也是可以马上连上，问题出现在连上之后一段时间内无法执行任何命令 你可以执行下面这段验证一下
> 
> ```
> adb disconnect 127.0.0.1:16384 && adb connect 127.0.0.1:16384 && adb shell settings get secure android_id
> ```
> 
> 如果明显需要等一段时间（我这是 30s）才能执行完毕就说明也是这个问题，可以参考 #9017 下面的一些方法临时绕过一下 大概的原理就是在 connect 之后再等一段时间开 MAA，这样这个延迟就没了

可以，下次该问题再次复现时我尝试一下
