### ISSUE TITLE
无法从设置界面进入maa官网

### ISSUE THREAD

**Issue by joshua0blake** [MaaAssistantArknights/MaaAssistantArknights#9103]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在设置界面点击官网就会出现错误弹窗
![XC`4C@P)11IN}EWB Z9T5E8](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125282918/b558d169-7fe4-42cf-b66c-2d240b3d3678)
下面这几个链接都是
![L`~_O XVHMBNHYGAS3CPJ{I](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125282918/73620b4e-f11b-4862-b48a-1f6486a0b7ec)
点击后
![V P2BS XY $ {X_Y FTS$E2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125282918/3bdd1a82-14de-4a72-a044-467b52b414b6)

错误信息

MAA 遇到了问题
An error occurred trying to start process 'https://www.maa.plus/' with working directory 'F:\MAA'. 找不到应用程序
解决方案
出现未知错误
详细信息
System.ComponentModel.Win32Exception (0x800401F5): An error occurred trying to start process 'https://www.maa.plus/' with working directory 'F:\MAA'. 找不到应用程序
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MaaWpfGui.App.Hyperlink_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Documents.Hyperlink.OnClick()
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

UI Version: v5.2.3
Core Version: v5.2.3
Resource Version: 慈悲灯塔

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15293862/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15293863/gui.log)

### 截图

![XC`4C@P)11IN}EWB Z9T5E8](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125282918/e984b017-156f-4322-b1a4-ffd50bb187f8)
![L`~_O XVHMBNHYGAS3CPJ{I](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125282918/3fd2f3df-3ce1-41fb-808d-95ceba836868)
![V P2BS XY $ {X_Y FTS$E2](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/125282918/0318d3d3-2e84-4449-85de-3747f5055fc5)

**Comment by Rbqwow** [comment]
设置一下默认浏览器

**Comment by ABA2396** [comment]
73a3ba7f4863e042c4ad6289affc3d219b0c163a fixed

**Comment by ABA2396** [comment]
![5a9fceeeafbf2fc58bdbf4d63c98d82a](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/6e38a06b-9083-4a1f-b11d-5b6e14270e30)
