### ISSUE TITLE
B服maa闪退，但官服没有问题

### ISSUE THREAD

**Issue by xuanwu666** [MaaAssistantArknights/MaaAssistantArknights#9124]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

我没有尝试重新安装运行库，因为官服可以正常运作。我重新下载maa后仍然会出问题。

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122015134/dcde14c4-8c2a-4aad-8a86-c0bc4e63f9a7)
maa界面如图，卡在这个界面不动，过一会就闪退；模拟器界面卡在刚打开模拟器的主界面上。
我自己用官服maa是从来没有出问题的。官服与B服的连接设置也一样。
当我使用minitouch或maatouch时（记不清了），闪退没有报错报告。当我切换到另一种连接方式时，会出现报错窗口。报错信息如下：System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass79_0.<ConnectToEmulator>b__3()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
﻿
应该是在最近一两周左右开始出现这个问题。以前从未有过。可能与我最近刚开始启用mumu截图增强或者使用maa文件夹内的adb文件替换adb（依照官方群的文档替换adb教程）有关（？）。但是关闭也没有用。

在刚刚。重启电脑之后maa依然不能正常执行任务。我尝试手动打开mumu模拟器，但是它在任务栏出现图标后，我不能在桌面上找到它。无论怎么在任务栏选中它都不行。但是我鼠标移到它的任务栏的图标上面，又会正常显示缩略图，似乎挺正常。当我在任务管理器将mumu相关进程都关闭并重启模拟器后，mumu仍然是这样会出问题，但是这次maa在使用B服时正常工作了。，推测可能与mumu管理器相关。（现在mumu是最新版本，但前几天不是）

我尝试过替换回旧版本maa，仍然不能避免出这个问题。

### Version

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122015134/3bc8dc8f-97cc-4613-8380-18093664308a)
Resource Version: 罗德岛促融共竞
UI Version: v5.2.4-alpha.1.d023.g76b03fdda
Core Version: v5.3.0-beta.1.d020.gb396f3722

### 日志文件

大概是在23.30左右。22点左右应该也出现了类似的问题。在22点之后我尝试更新了模拟器版本和maa版本，没有好转
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15337631/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15337637/gui.log)
在这之前的日子里的晚上十点应该大部分时候都出现过这个问题。从最近一周左右开始。

### 截图

debug文件夹内没有最近截图的图片

### 还有别的吗？

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/122015134/61840bd9-fac1-45c9-a072-1047db7f91c6)
电脑win11家庭版。笔记本4050，mumu12

禁止mumu联网以躲避广告。

某些时候，尽管模拟器仍然处于主界面，但maa右侧日志栏已经显示进行startup步骤了，在使用mumu增强模式且出现问题的情况下。

**Comment by xuanwu666** [comment]
报错信息不知怎的复制成我当时去搜的翻译了.....
报错信息如下：

System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass79_0.<ConnectToEmulator>b__3()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
﻿

**Comment by xuanwu666** [comment]
这样啊，那为什么官服是可以正常运行呢

**Comment by ABA2396** [comment]
不知道）现在的方法是提前一点时间启动模拟器（如果是maa开的话可以在设置里增加等待模拟器启动的时间），感觉最近挺多人因为给mumu断网报错的
