### ISSUE TITLE
5/18内测版出现gui类未知错误

### ISSUE THREAD

**Issue by constanji** [MaaAssistantArknights/MaaAssistantArknights#9145]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

打开maa就会立即出现如截图报错，且不会弹出maa窗口，之后我回退了内测版本依旧不行，不过出现弹窗报错是在开启maa后的10秒钟左右，之后换成了稳定版，总算正常
System.Runtime.InteropServices.COMException (0x8007139F)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.Notifications.IToastNotifierMethods.Show(IObjectReference _obj, ToastNotification notification)
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotifierCompat.Show(ToastNotification notification)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at MaaWpfGui.Helper.Notification.NotificationImplWinRT.ShowNotification(NotificationContent content)
   at MaaWpfGui.Helper.ToastNotification.Show(Double lifeTime, UInt32 row, NotificationSounds sound, NotificationHint[] hints)
   at MaaWpfGui.Models.ResourceUpdater.<>c.<CheckUpdateAsync>b__8_0()
   at Stylet.Execute.OnUIThreadAsync(Action action)
   at MaaWpfGui.Models.ResourceUpdater.CheckUpdateAsync(String baseUrl)
   at MaaWpfGui.Models.ResourceUpdater.UpdateAsync()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndDownloadUpdate()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.ShowUpdateOrDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 罗德岛促融共竞
UI Version: v5.3.0-beta.2
Core Version: v5.3.0-beta.2

### 日志文件

[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15365838/gui.log)
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15365840/asst.log)

### 截图

![303efeb4bbce0b09e1b6fab0fc0f0b61](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/108818150/f1a37d0d-0fcf-4c3e-9bd7-5aa9916355b1)

**Comment by constanji** [comment]
感谢您的解答，但是我并没有安装Kaspersky，内存也足够，目前是回退到稳定版正常使用了

**Comment by ABA2396** [comment]
cc @dantmnf  
#8960 改过了ToastNotification
