### ISSUE TITLE
打开MAA时提示通知平台不可用

### ISSUE THREAD

**Issue by xing-guang** [MaaAssistantArknights/MaaAssistantArknights#9208]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

win10启动MAA提示报错通知平台不可用，关闭窗口后程序退出，尝试重新下载最新版本仍不可用
报错信息如下：

MAA 遇到了问题
通知平台不可用。

通知平台不可用。

解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.COMException (0x803E0105): 通知平台不可用。

通知平台不可用。

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.Notifications.IToastNotificationManagerStaticsMethods.CreateToastNotifier(IObjectReference _obj, String applicationId)
   at Windows.UI.Notifications.ToastNotificationManager.CreateToastNotifier(String applicationId)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.CreateToastNotifier()
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show()
   at MaaWpfGui.Helper.Notification.NotificationImplWinRT.<>c__DisplayClass6_0.<ShowNotification>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at MaaWpfGui.Helper.Notification.NotificationImplWinRT.ShowNotification(NotificationContent content)
   at MaaWpfGui.Helper.ToastNotification.Show(Double lifeTime, UInt32 row, NotificationSounds sound, NotificationHint[] hints)
   at MaaWpfGui.Models.ResourceUpdater.<>c.<CheckUpdateAsync>b__8_0()
   at Stylet.Execute.OnUIThreadAsync(Action action)
   at MaaWpfGui.Models.ResourceUpdater.CheckUpdateAsync(String baseUrl)
   at MaaWpfGui.Models.ResourceUpdater.UpdateAsync()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndDownloadUpdate()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.ShowUpdateOrDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

MAA-v5.3.0-win-x64

### 日志文件

[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15444636/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15444637/gui.log)
[asst.bak.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15444638/asst.bak.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/59093673/d56d1914-3c7e-4a15-bbac-13d606a0518f)

### 还有别的吗？

win10 1809 早些时候还在正常使用 大约25号的20：30使用完毕后报错，尝试重启和重新下载均无法解决

**Comment by ABA2396** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/tag/v5.3.1 fixed
手动下个完整包覆盖下看看

**Comment by ABA2396** [comment]
[MAA-v5.3.1-win-x64.zip](https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v5.3.1/MAA-v5.3.1-win-x64.zip)
