### ISSUE TITLE
Maa遇到了问题，并且自动弹出了BUG反馈界面

### ISSUE THREAD

**Issue by QWQcool** [MaaAssistantArknights/MaaAssistantArknights#9218]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在我使用maa，点击开始任务时一直卡住在截图界面，于是我重启了maa点击开始任务后弹出此问题
弹出了如下消息
MAA 遇到了问题
External component has thrown an exception.
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass79_0.<ConnectToEmulator>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

MAA版本是V5.3.1

### 日志文件

大概是2024/5/27 13:10 ~13:20发生的问题
[asst.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15451165/asst.log)
[gui.log](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/15451166/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/87568799/abffaca3-b59a-4fe8-8604-ffa9bcd61099)

### 还有别的吗？

使用的mumu模拟器
win11操作系统
1660s显卡 13490kf cpu

**Comment by ABA2396** [comment]
有没有整过mumu屏蔽广告什么的
