### ISSUE TITLE
maa出现未知错误

### ISSUE THREAD

**Issue by typelimit** [MaaAssistantArknights/MaaAssistantArknights#9226]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开机自动启动时遇到障碍，必须手动去设置里面更改触控模式才可以，用笔记本自带的触控板控制驱动关闭触控板以后就会这样

### Version

v.5.3.1

### 日志文件

MAA 遇到了问题
External component has thrown an exception.
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass79_0.<ConnectToEmulator>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### 还有别的吗？

win11

**Comment by sunflower126** [comment]
我也遇到了类似的问题，maa在连接模拟器时弹出了报错的窗口，但与楼主不同的是，我的maa并非开机自启，而是由我自己在任务计划程序里设定的定时启动触发maa运行。希望能给maa制作组提供一点解决问题的思路。
![maa错误](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146410014/60351eec-daba-4947-b068-8c50279a0759)
![maa连接模拟器](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/146410014/26a5d9fb-c4c6-4f06-91a5-28a9fa0355ec)

**Comment by wuexbjjup448** [comment]
我用的是MuMu模拟器12，在上一次更新MuMu后遇到了这个错误。之后，我在模拟器设置里勾选“开启手机root权限”，就没有遇到上面的报错了。

**Comment by ABA2396** [comment]
新版mumu加了联网验证，刚打开的时候如果没连上网的话会执行不了adb命令，可能要提前几十秒到几分钟打开模拟器等这个验证超时才能连上。测试版加了重试机制，正式版现在可以先在设置里把那个等待模拟器启动时间延长一点

**Comment by Rbqwow** [comment]
新版本加了兜底策略 虽然解决不了 MuMu 的问题 但是 MAA 不会报错了
