### ISSUE TITLE
MAA启动出现未知错误

### ISSUE THREAD

**Issue by F16shen** [MaaAssistantArknights/MaaAssistantArknights#9302]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
External component has thrown an exception.
解决方案
出现未知错误
详细信息
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass79_0.<ConnectToEmulator>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

资源版本：生路
界面版本：5.3.1
核心版本：5.3.1

系统 ：win10

### 日志文件

2024年6月7日5点左右
[asst.log](https://github.com/user-attachments/files/15728866/asst.log)
[gui.log](https://github.com/user-attachments/files/15729340/gui.log)

### 还有别的吗？

模拟器MUMU12 版本V3.8.27

**Comment by ABA2396** [comment]
mumu之前更新加了联网检查，如果mumu无网络连接（比如为了屏蔽广告给mumu断网了）的话会有一段时间无法执行adb命令，要提前一段时间打开模拟器。内测版已经加了因为这个原因报错的处理，但该连不上还是连不上

**Comment by F16shen** [comment]
@ABA2396 看起来像是我自己的网络问题，我关了VPN之后重启电脑就好了

**Comment by Mowen-M** [comment]
> @ABA2396 看起来像是我自己的网络问题，我关了VPN之后重启电脑就好了

wc,我发现开VPN MUMU的adb开机会从16384变成16385，然后maa就自动检测不到了。折腾我两天，我以为maa问题
