### ISSUE TITLE
TimeSpan 周期报错

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [MaaAssistantArknights/MaaAssistantArknights#9331]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

在MAA任务执行完毕后报错，结束后无动作，无运行脚本。
报错：TimeSpan 周期必须大于或等于零。 (Parameter 'value')
```
System.ArgumentOutOfRangeException: TimeSpan 周期必须大于或等于零。 (Parameter 'value')
   at System.Windows.Threading.DispatcherTimer.set_Interval(TimeSpan value)
   at MaaWpfGui.Main.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### Version

资源版本：生路
UI版本：v5.4.0-beta1
核心版本：v5.4.0-beta1

### 日志文件

时间：06/09 11:34:54
[gui.log](https://github.com/user-attachments/files/15750454/gui.log)
[asst.log](https://github.com/user-attachments/files/15750453/asst.log)

### 还有别的吗？

模拟器：蓝叠模拟器5
操作系统：Windows 11
配置：虚拟化开启，hyper-v开启

**Comment by ABA2396** [comment]
b1ecfd83042e2c68dac2dadbcb026517a72253a9 fixed，现在使用的时候人为关注下，如果刷理智任务结束后理智大于等于最大理智-1的话会报错

**Comment by ABA2396** [comment]
> > 如果刷理智任务结束后理智大于等于最大理智-1的话会报错
> 
> 这没办法检测吗（

已经修了，还没发版
