### ISSUE TITLE
TimeSpan 周期必须大于或等于零。 (Parameter 'value')

### ISSUE THREAD

**Issue by AzukiiShirai** [MaaAssistantArknights/MaaAssistantArknights#9353]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
TimeSpan 周期必须大于或等于零。 (Parameter 'value')
解决方案
出现未知错误
详细信息
System.ArgumentOutOfRangeException: TimeSpan 周期必须大于或等于零。 (Parameter 'value')
   at System.Windows.Threading.DispatcherTimer.set_Interval(TimeSpan value)
   at MaaWpfGui.Main.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15782615/asst.log)
[gui.log](https://github.com/user-attachments/files/15782616/gui.log)

**Comment by Rbqwow** [comment]
duplicate of #9331

b1ecfd83042e2c68dac2dadbcb026517a72253a9 fixed
