### ISSUE TITLE
MAA闪退打不开了

### ISSUE THREAD

**Issue by Clanand233** [MaaAssistantArknights/MaaAssistantArknights#9372]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

之前用MAA会用着用着突然自动重启，看CPU内存占用也不高，就是突然的黑屏。今天一样的黑屏重启以后MAA就打不开，打开就提示遇到问题

### Version

MAA打不开 是最新版

### 日志文件

[asst.log](https://github.com/user-attachments/files/15817728/asst.log)
[gui.log](https://github.com/user-attachments/files/15817732/gui.log)

### 还有别的吗？

MAA 遇到了问题
The type initializer for 'MaaWpfGui.Helper.DataHelper' threw an exception.
Error reading JObject from JsonReader. Path '', line 1, position 349292.
解决方案
请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.Helper.DataHelper' threw an exception.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 349292.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at MaaWpfGui.Helper.DataHelper..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.Helper.DataHelper.GetLocalizedCharacterName(String characterName, String language)
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.UpdateRoguelikeCoreCharList()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.InitRoguelike()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel.Init()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Clanand233** [comment]
mumu12  win10

**Comment by ABA2396** [comment]
黑屏的问题找电脑售后，这个问题跟着文档去装运行库
