### ISSUE TITLE
MAA 遇到了问题"找不到指定的模块。 (0x8007007E)"

### ISSUE THREAD

**Issue by Likeqin96** [MaaAssistantArknights/MaaAssistantArknights#9383]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA无法打开，显示The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
但是我确定MaaCore.dll存在
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/130019113/f1288087-14cb-40d7-a8f6-22be0e8cbf68)
MAA已经重装过问题依然存在

### Version

MAA-v5.3.1-win-x64

### 日志文件

[gui.log](https://github.com/user-attachments/files/15833048/gui.log)

MAA 遇到了问题
The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
解决方案
请参考文档: 常见问题 - 闪退 进行操作。
详细信息
System.TypeInitializationException: The type initializer for 'MaaWpfGui.ViewModels.UI.SettingsViewModel' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'MaaCore.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
   at MaaWpfGui.Services.MaaService.AsstGetVersion()
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..cctor()
   --- End of inner exception stack trace ---
   at MaaWpfGui.ViewModels.UI.SettingsViewModel..ctor()
   at lambda_method13(Closure, IRegistrationContext)
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at StyletIoC.Internal.Container.Get[T](String key)
   at MaaWpfGui.Helper.Instances.Instantiate(IContainer container)
   at MaaWpfGui.Main.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at MaaWpfGui.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ABA2396** [comment]
请参考文档: 常见问题 - 闪退 进行操作。
