### ISSUE TITLE
Stuck while connecting to emulator

### ISSUE THREAD

**Issue by minkuuuu** [MaaAssistantArknights/MaaAssistantArknights#9410]
### Before raising the issue...

- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

Link start and the problem happen

### Version

Resource Version: Il Siracusano - Retrospection
UI Version: v5.3.1
Core Version: v5.3.1

### Log files

[asst.log](https://github.com/user-attachments/files/15873859/asst.log)
[gui.log](https://github.com/user-attachments/files/15873860/gui.log)
Time stamp: 2024-06-17 23:02:56.651

### Screenshots

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/165810720/09640a3e-2cf7-4202-a0a9-ae7ad631338a)

Error Message:
MAA has encountered an error
External component has thrown an exception.
Solution
Unknown error occurred
Details
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at MaaWpfGui.Services.MaaService.AsstConnect(IntPtr handle, Byte* adbPath, Byte* address, Byte* config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(IntPtr handle, String adbPath, String address, String config)
   at MaaWpfGui.Main.AsstProxy.AsstConnect(String& error)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.<>c__DisplayClass79_0.<ConnectToEmulator>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.ConnectToEmulator()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Anthing else?

Windows 10 22H2
Mumuplayer v3.8.18

**Comment by Rbqwow** [comment]
have you tried restarting the computer?
the log looks weird

**Comment by minkuuuu** [comment]
> have you tried restarting the computer? the log looks weird

I tried a few times and sometimes it connects normally but also sometime it behaved weirdly that way. I updated the screenshot and the error message as well.

**Comment by Rbqwow** [comment]
MuMuPlayer will timeout adb connection when no internet connection

adb will only be available 30 to 60 seconds after MuMu startup

Beta version of maa now handle this situation correctly but we cannot solve the timeout issue of mumu
