### ISSUE TITLE
OTA更新The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by KawausoJyou** [MaaAssistantArknights/MaaAssistantArknights#9412]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

> OTA更新时必定出现此错误，手动解压OTA压缩包后启动MAA也会出现此错误。
> 已经安装最新版本的两个运行库。

MAA 遇到了问题
The process cannot access the file because it is being used by another process.
解决方案
出现未知错误
详细信息
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndUpdateNow()
   at MaaWpfGui.ViewModels.UI.RootViewModel.OnViewLoaded()
   at Stylet.Screen.<Stylet.IViewAware.AttachView>b__42_0(Object o, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1.d035.gd2e5001e7
Core Version: v5.4.0-beta.1.d035.gd2e5001e7

### 日志文件

[asst.log](https://github.com/user-attachments/files/15879573/asst.log)
[gui.log](https://github.com/user-attachments/files/15879574/gui.log)

2024/6/18 10:20附近

**Comment by ABA2396** [comment]
文件被别的应用占了，手动解压下压缩包然后删掉
