### ISSUE TITLE
TimeSpan period报错，在未规定作战关卡时出现未知错误

### ISSUE THREAD

**Issue by MilarvozM** [MaaAssistantArknights/MaaAssistantArknights#9417]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

忘了活动已经关闭，自动作战已经回到了默认的当前/之前未设置，不确定具体问题发生时间点但应该就是关卡作战部分，其他的公招以及mall都正常完成，关闭错误弹窗后MAA整体关闭

错误弹窗信息如下：
MAA 遇到了问题
TimeSpan period must be greater than or equal to zero. (Parameter 'value')
解决方案
出现未知错误
详细信息

System.ArgumentOutOfRangeException: TimeSpan period must be greater than or equal to zero. (Parameter 'value')
   at System.Windows.Threading.DispatcherTimer.set_Interval(TimeSpan value)
   at MaaWpfGui.Main.AsstProxy.ProcTaskChainMsg(AsstMsg msg, JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 生路
UI Version: v5.4.0-beta.1
Core Version: v5.4.0-beta.1

### 日志文件

[asst.log](https://github.com/user-attachments/files/15892982/asst.log)
[gui.log](https://github.com/user-attachments/files/15892984/gui.log)
2024-06-18 14点之后的第一次启动是问题发生的部分（关闭后为了复制版本号再次启动过）

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/34495348/742837a7-88d1-48a0-be2c-456d8a1a625b)

### 还有别的吗？

使用的mrfz官网给的mumu模拟器版本
[DxDiag.txt](https://github.com/user-attachments/files/15893041/DxDiag.txt)

**Comment by ABA2396** [comment]
b1ecfd83042e2c68dac2dadbcb026517a72253a9 fixed
