### ISSUE TITLE
开机自启MAA过程中报错，但不影响后续运行

### ISSUE THREAD

**Issue by zenoangel** [MaaAssistantArknights/MaaAssistantArknights#9564]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

开机自启后出现了报错：
MAA 遇到了问题
The process cannot access the file 'D:\arknights\MAA-v4.24.0-win-x64\resource\Arknights-Tile-Pos\overview.json.tmp' because it is being used by another process.
解决方案
出现未知错误
详细信息
System.IO.IOException: The process cannot access the file 'D:\arknights\MAA-v4.24.0-win-x64\resource\Arknights-Tile-Pos\overview.json.tmp' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at MaaWpfGui.Helper.HttpResponseHelper.SaveResponseToFileAsync(HttpResponseMessage response, String saveTo, Boolean saveAndDeleteTmp)
   at MaaWpfGui.Models.ResourceUpdater.UpdateFileWithETagAsync(String baseUrl, String file, String saveTo, Int32 maxRetryTime)
   at MaaWpfGui.Models.ResourceUpdater.UpdateSingleFilesAsync(String baseUrl, Int32 maxRetryTime)
   at MaaWpfGui.Models.ResourceUpdater.UpdateAsync()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.CheckAndDownloadUpdate()
   at MaaWpfGui.ViewModels.UI.VersionUpdateViewModel.ShowUpdateOrDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

运行正常，关闭再启动程序后没有再报错

### Version

Resource Version: 空想花庭·复刻
UI Version: v5.4.0
Core Version: v5.4.0

### 日志文件

[asst.log](https://github.com/user-attachments/files/16126896/asst.log)
[gui.log](https://github.com/user-attachments/files/16126898/gui.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/53809240/3e8a7486-2e24-46c4-a691-53bee3e56a52)
![Uploading image.png…]()

### 还有别的吗？

模拟器mumu12，Win11

**Comment by ABA2396** [comment]
![image](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/99072975/99efbcac-cb82-4c20-bb9d-eef496ddb77e)
文件被占用了，有没有同时开多个

**Comment by zenoangel** [comment]
> ![image](https://private-user-images.githubusercontent.com/99072975/346547261-99efbcac-cb82-4c20-bb9d-eef496ddb77e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mzk2NDQsIm5iZiI6MTcyMDQzOTM0NCwicGF0aCI6Ii85OTA3Mjk3NS8zNDY1NDcyNjEtOTllZmJjYWMtY2I4Mi00YzIwLWJiOWQtZWVmNDk2ZGRiNzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDExNDkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZDdlZmZjNzg1MzVhYzQ1MGVlOTc4NmRkNzVlYTdjMjM1ZDFlMzU0NzcxZjY0NjczM2QyYzI4NzE2NDk4ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dl_B0xFh63ZF4hzd4TxrimFvDQgSAUM9At-5s-NeaBk) 文件被占用了，有没有同时开多个

没有，开机后甚至鼠标都没动

**Comment by wanniwa** [comment]
我这边也是启动自动更新，自动重启后就报这个错

**Comment by Rbqwow** [comment]
重装一次 MAA 试试

只需要保留 /config/gui.json 这一个文件
