### ISSUE TITLE
运行肉鸽存钱突然报错

### ISSUE THREAD

**Issue by messasiye** [MaaAssistantArknights/MaaAssistantArknights#9571]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskStart(JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

UI Version: v5.4.1-alpha.1.d022.ga340d515a

### 日志文件

[asst.log](https://github.com/user-attachments/files/16130814/asst.log)
[gui.log](https://github.com/user-attachments/files/16130816/gui.log)

**Comment by Constrat** [comment]
Dupe 	#9559
