### ISSUE TITLE
打薩米的時候出現了這個錯誤 maa就關掉了

### ISSUE THREAD

**Issue by chanchunon** [MaaAssistantArknights/MaaAssistantArknights#9587]
### 在提问之前...

- [ ] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [ ] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [ ] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了問題
Value cannot be null. (Parameter 'value')
解決方法
出現未知錯誤
詳細資訊
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskStart(JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Version

Resource Version: 火山旅夢
UI Version: v5.4.1-alpha.1.d022.ga340d515a
Core Version: v5.4.1-alpha.1.d022.ga340d515a

### 日志文件

[gui.log](https://github.com/user-attachments/files/16143678/gui.log)
[asst.log](https://github.com/user-attachments/files/16143679/asst.log)

**Comment by Rbqwow** [comment]
duplicate of #9559
