### ISSUE TITLE
MAA遇到了問題 今天更新後才有的

### ISSUE THREAD

**Issue by lioncai666** [MaaAssistantArknights/MaaAssistantArknights#9606]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [ ] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了問題
Value cannot be null. (Parameter 'value')
解決方法
出現未知錯誤
詳細資訊
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at MaaWpfGui.Main.AsstProxy.ProcSubTaskStart(JObject details)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
![螢幕擷取畫面 2024-07-10 170909](https://github.com/MaaAssistantArknights/MaaAssistantArknights/assets/175203035/35fec775-0290-47c1-ac48-da368b64c57c)

### Version

Core Version: v5.4.1-alpha.1.d042.g1b8911f55

### 日志文件

[asst.log](https://github.com/user-attachments/files/16158483/asst.log)
[gui.log](https://github.com/user-attachments/files/16158484/gui.log)
一直出現報錯

**Comment by Constrat** [comment]
Duplicate of #9559
PINNED ISSUE!
