### ISSUE TITLE
基建换班错误 Attempted to divide by zero

### ISSUE THREAD

**Issue by emiyax** [MaaAssistantArknights/MaaAssistantArknights#9837]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 Bug 已被修复的情况
- [X] 我已检查了置顶议题（pinned issue），确认我的问题未被提及

### 问题描述

MAA 遇到了问题
Attempted to divide by zero.
解决方案
出现未知错误
详细信息
System.DivideByZeroException: Attempted to divide by zero.
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.set_CustomInfrastPlanIndex(Int32 value)
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.get_CustomInfrastPlanIndex()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.AppendInfrast()
   at MaaWpfGui.ViewModels.UI.TaskQueueViewModel.LinkStart()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
选择基建换班时发生，更新Core Version: v5.5.0-beta.1.d109.g50ddefa76后出现。
没有使用自定义基建配置。

### Version

Resource Version: 熔炉“还魂”记
UI Version: v5.5.0-beta.1.d109.g50ddefa76
Core Version: v5.5.0-beta.1.d109.g50ddefa76

### 日志文件

[asst.log](https://github.com/user-attachments/files/16327088/asst.log)
[gui.log](https://github.com/user-attachments/files/16327090/gui.log)
时间点为2024-07-22 10:10

### 截图

![屏幕截图 2024-07-22 101326](https://github.com/user-attachments/assets/eabbcc0a-ea4d-4058-8170-95452530558a)

### 还有别的吗？

可复现错误。
更新Core Version: v5.5.0-beta.1.d109.g50ddefa76出现。
可能与“一个参数越界的错误 #9779”相关。

**Comment by Saratoga-Official** [comment]
这个是除零错误，尝试将某个数值除于零，除不了报错，检查一下基建设置是不是存在问题

**Comment by emiyax** [comment]
![屏幕截图 2024-07-22 103439](https://github.com/user-attachments/assets/a8fa6e9c-af97-4fa4-b7c7-94bfc3bdf752)
![屏幕截图 2024-07-22 103550](https://github.com/user-attachments/assets/19e0be09-11c9-49e7-b47d-caaaba3999f6)
与之前版本比较，没有改变选项。没有启用自定义。请问一下，应该是可以不选某些设置的吧。

**Comment by ABA2396** [comment]
423a37bfbbc1c24b09d412a28436a9ff55eb864f 85f1a719a326476853bf23f156718a17b51f5d3c fixed
等待 action https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/10033837247
